<a href="https://colab.research.google.com/github/atshaya1208/Stock_Analysis_data/blob/main/modstock.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import os
import yaml

In [2]:
!unzip stock_data.zip

Archive:  stock_data.zip
   creating: stock_data/
  inflating: stock_data/2023-10-03_05-30-00.yaml
  inflating: stock_data/2023-10-04_05-30-00.yaml
  inflating: stock_data/2023-10-05_05-30-00.yaml
  inflating: stock_data/2023-10-06_05-30-00.yaml
  inflating: stock_data/2023-10-09_05-30-00.yaml
  inflating: stock_data/2023-10-10_05-30-00.yaml
  inflating: stock_data/2023-10-11_05-30-00.yaml
  inflating: stock_data/2023-10-12_05-30-00.yaml
  inflating: stock_data/2023-10-13_05-30-00.yaml
  inflating: stock_data/2023-10-16_05-30-00.yaml
  inflating: stock_data/2023-10-17_05-30-00.yaml
  inflating: stock_data/2023-10-18_05-30-00.yaml
  inflating: stock_data/2023-10-19_05-30-00.yaml
  inflating: stock_data/2023-10-20_05-30-00.yaml
  inflating: stock_data/2023-10-23_05-30-00.yaml
  inflating: stock_data/2023-10-25_05-30-00.yaml
  inflating: stock_data/2023-10-26_05-30-00.yaml
  inflating: stock_data/2023-10-27_05-30-00.yaml
  inflating: stock_data/2023-10-30_05-30-00.yaml
  inflating: stock_data/2023-10-31_05-30-00.yaml
  inflating: stock_data/2023-11-01_05-30-00.yaml
  inflating: stock_data/2023-11-02_05-30-00.yaml
  inflating: stock_data/2023-11-03_05-30-00.yaml
  inflating: stock_data/2023-11-06_05-30-00.yaml
  inflating: stock_data/2023-11-07_05-30-00.yaml
  inflating: stock_data/2023-11-08_05-30-00.yaml
  inflating: stock_data/2023-11-09_05-30-00.yaml
  inflating: stock_data/2023-11-10_05-30-00.yaml
  inflating: stock_data/2023-11-12_05-30-00.yaml
  inflating: stock_data/2023-11-13_05-30-00.yaml
  inflating: stock_data/2023-11-15_05-30-00.yaml
  inflating: stock_data/2023-11-16_05-30-00.yaml
  inflating: stock_data/2023-11-17_05-30-00.yaml
  inflating: stock_data/2023-11-20_05-30-00.yaml
  inflating: stock_data/2023-11-21_05-30-00.yaml
  inflating: stock_data/2023-11-22_05-30-00.yaml
  inflating: stock_data/2023-11-23_05-30-00.yaml
  inflating: stock_data/2023-11-24_05-30-00.yaml
  inflating: stock_data/2023-11-28_05-30-00.yaml
  inflating: stock_data/2023-11-29_05-30-00.yaml
  inflating: stock_data/2023-11-30_05-30-00.yaml
  inflating: stock_data/2023-12-01_05-30-00.yaml
  inflating: stock_data/2023-12-04_05-30-00.yaml
  inflating: stock_data/2023-12-05_05-30-00.yaml
  inflating: stock_data/2023-12-06_05-30-00.yaml
  inflating: stock_data/2023-12-07_05-30-00.yaml
  inflating: stock_data/2023-12-08_05-30-00.yaml
  inflating: stock_data/2023-12-11_05-30-00.yaml
  inflating: stock_data/2023-12-12_05-30-00.yaml
  inflating: stock_data/2023-12-13_05-30-00.yaml
  inflating: stock_data/2023-12-14_05-30-00.yaml
  inflating: stock_data/2023-12-15_05-30-00.yaml
  inflating: stock_data/2023-12-18_05-30-00.yaml
  inflating: stock_data/2023-12-19_05-30-00.yaml
  inflating: stock_data/2023-12-20_05-30-00.yaml
  inflating: stock_data/2023-12-21_05-30-00.yaml
  inflating: stock_data/2023-12-22_05-30-00.yaml
  inflating: stock_data/2023-12-26_05-30-00.yaml
  inflating: stock_data/2023-12-27_05-30-00.yaml
  inflating: stock_data/2023-12-28_05-30-00.yaml
  inflating: stock_data/2023-12-29_05-30-00.yaml
  inflating: stock_data/2024-01-01_05-30-00.yaml
  inflating: stock_data/2024-01-02_05-30-00.yaml
  inflating: stock_data/2024-01-03_05-30-00.yaml
  inflating: stock_data/2024-01-04_05-30-00.yaml
  inflating: stock_data/2024-01-05_05-30-00.yaml
  inflating: stock_data/2024-01-08_05-30-00.yaml
  inflating: stock_data/2024-01-09_05-30-00.yaml
  inflating: stock_data/2024-01-10_05-30-00.yaml
  inflating: stock_data/2024-01-11_05-30-00.yaml
  inflating: stock_data/2024-01-12_05-30-00.yaml
  inflating: stock_data/2024-01-15_05-30-00.yaml
  inflating: stock_data/2024-01-16_05-30-00.yaml
  inflating: stock_data/2024-01-17_05-30-00.yaml
  inflating: stock_data/2024-01-18_05-30-00.yaml
  inflating: stock_data/2024-01-19_05-30-00.yaml
  inflating: stock_data/2024-01-20_05-30-00.yaml
  inflating: stock_data/2024-01-23_05-30-00.yaml
  inflating: stock_data/2024-01-24_05-30-00.yaml
  inflating: stock_data/2024-01-25_05-30-00.yaml
  inflating: stock_data/2024-01-29_05-30-00.yaml
  inflating: stock_data/2024-01-30_05-30-00.yaml
  inflating: stock_data/2024-01-31_05-30-00.yaml
  inflating: stock_data/2024-02-01_05-30-00.yaml
  inflating: stock_data/2024-02-02_05-30-00.yaml
  inflating: stock_data/2024-02-05_05-30-00.yaml
  inflating: stock_data/2024-02-06_05-30-00.yaml
  inflating: stock_data/2024-02-07_05-30-00.yaml
  inflating: stock_data/2024-02-08_05-30-00.yaml
  inflating: stock_data/2024-02-09_05-30-00.yaml
  inflating: stock_data/2024-02-12_05-30-00.yaml
  inflating: stock_data/2024-02-13_05-30-00.yaml
  inflating: stock_data/2024-02-14_05-30-00.yaml
  inflating: stock_data/2024-02-15_05-30-00.yaml
  inflating: stock_data/2024-02-16_05-30-00.yaml
  inflating: stock_data/2024-02-19_05-30-00.yaml
  inflating: stock_data/2024-02-20_05-30-00.yaml
  inflating: stock_data/2024-02-21_05-30-00.yaml
  inflating: stock_data/2024-02-22_05-30-00.yaml
  inflating: stock_data/2024-02-23_05-30-00.yaml
  inflating: stock_data/2024-02-26_05-30-00.yaml
  inflating: stock_data/2024-02-27_05-30-00.yaml
  inflating: stock_data/2024-02-28_05-30-00.yaml
  inflating: stock_data/2024-02-29_05-30-00.yaml
  inflating: stock_data/2024-03-01_05-30-00.yaml
  inflating: stock_data/2024-03-02_05-30-00.yaml
  inflating: stock_data/2024-03-04_05-30-00.yaml
  inflating: stock_data/2024-03-05_05-30-00.yaml
  inflating: stock_data/2024-03-06_05-30-00.yaml
  inflating: stock_data/2024-03-07_05-30-00.yaml
  inflating: stock_data/2024-03-11_05-30-00.yaml
  inflating: stock_data/2024-03-12_05-30-00.yaml
  inflating: stock_data/2024-03-13_05-30-00.yaml
  inflating: stock_data/2024-03-14_05-30-00.yaml
  inflating: stock_data/2024-03-15_05-30-00.yaml
  inflating: stock_data/2024-03-18_05-30-00.yaml
  inflating: stock_data/2024-03-19_05-30-00.yaml
  inflating: stock_data/2024-03-20_05-30-00.yaml
  inflating: stock_data/2024-03-21_05-30-00.yaml
  inflating: stock_data/2024-03-22_05-30-00.yaml
  inflating: stock_data/2024-03-26_05-30-00.yaml
  inflating: stock_data/2024-03-27_05-30-00.yaml
  inflating: stock_data/2024-03-28_05-30-00.yaml
  inflating: stock_data/2024-04-01_05-30-00.yaml
  inflating: stock_data/2024-04-02_05-30-00.yaml
  inflating: stock_data/2024-04-03_05-30-00.yaml
  inflating: stock_data/2024-04-04_05-30-00.yaml
  inflating: stock_data/2024-04-05_05-30-00.yaml
  inflating: stock_data/2024-04-08_05-30-00.yaml
  inflating: stock_data/2024-04-09_05-30-00.yaml
  inflating: stock_data/2024-04-10_05-30-00.yaml
  inflating: stock_data/2024-04-12_05-30-00.yaml
  inflating: stock_data/2024-04-15_05-30-00.yaml
  inflating: stock_data/2024-04-16_05-30-00.yaml
  inflating: stock_data/2024-04-18_05-30-00.yaml
  inflating: stock_data/2024-04-19_05-30-00.yaml
  inflating: stock_data/2024-04-22_05-30-00.yaml
  inflating: stock_data/2024-04-23_05-30-00.yaml
  inflating: stock_data/2024-04-24_05-30-00.yaml
  inflating: stock_data/2024-04-25_05-30-00.yaml
  inflating: stock_data/2024-04-26_05-30-00.yaml
  inflating: stock_data/2024-04-29_05-30-00.yaml
  inflating: stock_data/2024-04-30_05-30-00.yaml
  inflating: stock_data/2024-05-02_05-30-00.yaml
  inflating: stock_data/2024-05-03_05-30-00.yaml
  inflating: stock_data/2024-05-06_05-30-00.yaml
  inflating: stock_data/2024-05-07_05-30-00.yaml
  inflating: stock_data/2024-05-08_05-30-00.yaml
  inflating: stock_data/2024-05-09_05-30-00.yaml
  inflating: stock_data/2024-05-10_05-30-00.yaml
  inflating: stock_data/2024-05-13_05-30-00.yaml
  inflating: stock_data/2024-05-14_05-30-00.yaml
  inflating: stock_data/2024-05-15_05-30-00.yaml
  inflating: stock_data/2024-05-16_05-30-00.yaml
  inflating: stock_data/2024-05-17_05-30-00.yaml
  inflating: stock_data/2024-05-18_05-30-00.yaml
  inflating: stock_data/2024-05-21_05-30-00.yaml
  inflating: stock_data/2024-05-22_05-30-00.yaml
  inflating: stock_data/2024-05-23_05-30-00.yaml
  inflating: stock_data/2024-05-24_05-30-00.yaml
  inflating: stock_data/2024-05-27_05-30-00.yaml
  inflating: stock_data/2024-05-28_05-30-00.yaml
  inflating: stock_data/2024-05-29_05-30-00.yaml
  inflating: stock_data/2024-05-30_05-30-00.yaml
  inflating: stock_data/2024-05-31_05-30-00.yaml
  inflating: stock_data/2024-06-03_05-30-00.yaml
  inflating: stock_data/2024-06-04_05-30-00.yaml
  inflating: stock_data/2024-06-05_05-30-00.yaml
  inflating: stock_data/2024-06-06_05-30-00.yaml
  inflating: stock_data/2024-06-07_05-30-00.yaml
  inflating: stock_data/2024-06-10_05-30-00.yaml
  inflating: stock_data/2024-06-11_05-30-00.yaml
  inflating: stock_data/2024-06-12_05-30-00.yaml
  inflating: stock_data/2024-06-13_05-30-00.yaml
  inflating: stock_data/2024-06-14_05-30-00.yaml
  inflating: stock_data/2024-06-18_05-30-00.yaml
  inflating: stock_data/2024-06-19_05-30-00.yaml
  inflating: stock_data/2024-06-20_05-30-00.yaml
  inflating: stock_data/2024-06-21_05-30-00.yaml
  inflating: stock_data/2024-06-24_05-30-00.yaml
  inflating: stock_data/2024-06-25_05-30-00.yaml
  inflating: stock_data/2024-06-26_05-30-00.yaml
  inflating: stock_data/2024-06-27_05-30-00.yaml
  inflating: stock_data/2024-06-28_05-30-00.yaml
  inflating: stock_data/2024-07-01_05-30-00.yaml
  inflating: stock_data/2024-07-02_05-30-00.yaml
  inflating: stock_data/2024-07-03_05-30-00.yaml
  inflating: stock_data/2024-07-04_05-30-00.yaml
  inflating: stock_data/2024-07-05_05-30-00.yaml
  inflating: stock_data/2024-07-08_05-30-00.yaml
  inflating: stock_data/2024-07-09_05-30-00.yaml
  inflating: stock_data/2024-07-10_05-30-00.yaml
  inflating: stock_data/2024-07-11_05-30-00.yaml
  inflating: stock_data/2024-07-12_05-30-00.yaml
  inflating: stock_data/2024-07-15_05-30-00.yaml
  inflating: stock_data/2024-07-16_05-30-00.yaml
  inflating: stock_data/2024-07-18_05-30-00.yaml
  inflating: stock_data/2024-07-19_05-30-00.yaml
  inflating: stock_data/2024-07-22_05-30-00.yaml
  inflating: stock_data/2024-07-23_05-30-00.yaml
  inflating: stock_data/2024-07-24_05-30-00.yaml
  inflating: stock_data/2024-07-25_05-30-00.yaml
  inflating: stock_data/2024-07-26_05-30-00.yaml
  inflating: stock_data/2024-07-29_05-30-00.yaml
  inflating: stock_data/2024-07-30_05-30-00.yaml
  inflating: stock_data/2024-07-31_05-30-00.yaml
  inflating: stock_data/2024-08-01_05-30-00.yaml
  inflating: stock_data/2024-08-02_05-30-00.yaml
  inflating: stock_data/2024-08-05_05-30-00.yaml
  inflating: stock_data/2024-08-06_05-30-00.yaml
  inflating: stock_data/2024-08-07_05-30-00.yaml
  inflating: stock_data/2024-08-08_05-30-00.yaml
  inflating: stock_data/2024-08-09_05-30-00.yaml
  inflating: stock_data/2024-08-12_05-30-00.yaml
  inflating: stock_data/2024-08-13_05-30-00.yaml
  inflating: stock_data/2024-08-14_05-30-00.yaml
  inflating: stock_data/2024-08-16_05-30-00.yaml
  inflating: stock_data/2024-08-19_05-30-00.yaml
  inflating: stock_data/2024-08-20_05-30-00.yaml
  inflating: stock_data/2024-08-21_05-30-00.yaml
  inflating: stock_data/2024-08-22_05-30-00.yaml
  inflating: stock_data/2024-08-23_05-30-00.yaml
  inflating: stock_data/2024-08-26_05-30-00.yaml
  inflating: stock_data/2024-08-27_05-30-00.yaml
  inflating: stock_data/2024-08-28_05-30-00.yaml
  inflating: stock_data/2024-08-29_05-30-00.yaml
  inflating: stock_data/2024-08-30_05-30-00.yaml
  inflating: stock_data/2024-09-02_05-30-00.yaml
  inflating: stock_data/2024-09-03_05-30-00.yaml
  inflating: stock_data/2024-09-04_05-30-00.yaml
  inflating: stock_data/2024-09-05_05-30-00.yaml
  inflating: stock_data/2024-09-06_05-30-00.yaml
  inflating: stock_data/2024-09-09_05-30-00.yaml
  inflating: stock_data/2024-09-10_05-30-00.yaml
  inflating: stock_data/2024-09-11_05-30-00.yaml
  inflating: stock_data/2024-09-12_05-30-00.yaml
  inflating: stock_data/2024-09-13_05-30-00.yaml
  inflating: stock_data/2024-09-16_05-30-00.yaml
  inflating: stock_data/2024-09-17_05-30-00.yaml
  inflating: stock_data/2024-09-18_05-30-00.yaml
  inflating: stock_data/2024-09-19_05-30-00.yaml
  inflating: stock_data/2024-09-20_05-30-00.yaml
  inflating: stock_data/2024-09-23_05-30-00.yaml
  inflating: stock_data/2024-09-24_05-30-00.yaml
  inflating: stock_data/2024-09-25_05-30-00.yaml
  inflating: stock_data/2024-09-26_05-30-00.yaml
  inflating: stock_data/2024-09-27_05-30-00.yaml
  inflating: stock_data/2024-09-30_05-30-00.yaml
  inflating: stock_data/2024-10-01_05-30-00.yaml
  inflating: stock_data/2024-10-03_05-30-00.yaml
  inflating: stock_data/2024-10-04_05-30-00.yaml
  inflating: stock_data/2024-10-07_05-30-00.yaml
  inflating: stock_data/2024-10-08_05-30-00.yaml
  inflating: stock_data/2024-10-09_05-30-00.yaml
  inflating: stock_data/2024-10-10_05-30-00.yaml
  inflating: stock_data/2024-10-11_05-30-00.yaml
  inflating: stock_data/2024-10-14_05-30-00.yaml
  inflating: stock_data/2024-10-15_05-30-00.yaml
  inflating: stock_data/2024-10-16_05-30-00.yaml
  inflating: stock_data/2024-10-17_05-30-00.yaml
  inflating: stock_data/2024-10-18_05-30-00.yaml
  inflating: stock_data/2024-10-21_05-30-00.yaml
  inflating: stock_data/2024-10-22_05-30-00.yaml
  inflating: stock_data/2024-10-23_05-30-00.yaml
  inflating: stock_data/2024-10-24_05-30-00.yaml
  inflating: stock_data/2024-10-25_05-30-00.yaml
  inflating: stock_data/2024-10-28_05-30-00.yaml
  inflating: stock_data/2024-10-29_05-30-00.yaml
  inflating: stock_data/2024-10-30_05-30-00.yaml
  inflating: stock_data/2024-10-31_05-30-00.yaml
  inflating: stock_data/2024-11-01_05-30-00.yaml
  inflating: stock_data/2024-11-04_05-30-00.yaml
  inflating: stock_data/2024-11-05_05-30-00.yaml
  inflating: stock_data/2024-11-06_05-30-00.yaml
  inflating: stock_data/2024-11-07_05-30-00.yaml
  inflating: stock_data/2024-11-08_05-30-00.yaml
  inflating: stock_data/2024-11-11_05-30-00.yaml
  inflating: stock_data/2024-11-12_05-30-00.yaml
  inflating: stock_data/2024-11-13_05-30-00.yaml
  inflating: stock_data/2024-11-14_05-30-00.yaml
  inflating: stock_data/2024-11-18_05-30-00.yaml
  inflating: stock_data/2024-11-19_05-30-00.yaml
  inflating: stock_data/2024-11-21_05-30-00.yaml
  inflating: stock_data/2024-11-22_05-30-00.yaml

In [3]:
search_path = "/content/stock_data"

yaml_files = []

for root, dirs, files in os.walk(search_path):
    for file in files:
        if file.lower().endswith(('.yaml')):
            full_path = os.path.join(root, file)
            yaml_files.append(full_path)

print(f"Found {len(yaml_files)} YAML files:")

Found 284 YAML files:

In [4]:
for file in yaml_files:
    print(file)

/content/stock_data/2024-06-26_05-30-00.yaml
/content/stock_data/2023-11-21_05-30-00.yaml
/content/stock_data/2023-10-11_05-30-00.yaml
/content/stock_data/2024-08-14_05-30-00.yaml
/content/stock_data/2024-10-14_05-30-00.yaml
/content/stock_data/2024-03-14_05-30-00.yaml
/content/stock_data/2024-01-12_05-30-00.yaml
/content/stock_data/2024-09-24_05-30-00.yaml
/content/stock_data/2024-04-29_05-30-00.yaml
/content/stock_data/2023-11-24_05-30-00.yaml
/content/stock_data/2023-11-15_05-30-00.yaml
/content/stock_data/2024-04-26_05-30-00.yaml
/content/stock_data/2023-12-15_05-30-00.yaml
/content/stock_data/2023-12-05_05-30-00.yaml
/content/stock_data/2024-06-10_05-30-00.yaml
/content/stock_data/2023-10-05_05-30-00.yaml
/content/stock_data/2024-07-05_05-30-00.yaml
/content/stock_data/2024-05-03_05-30-00.yaml
/content/stock_data/2024-02-21_05-30-00.yaml
/content/stock_data/2024-02-08_05-30-00.yaml
/content/stock_data/2024-09-16_05-30-00.yaml
/content/stock_data/2023-11-07_05-30-00.yaml
/content/stock_data/2024-02-14_05-30-00.yaml
/content/stock_data/2024-05-07_05-30-00.yaml
/content/stock_data/2024-06-06_05-30-00.yaml
/content/stock_data/2024-02-20_05-30-00.yaml
/content/stock_data/2024-10-29_05-30-00.yaml
/content/stock_data/2023-10-30_05-30-00.yaml
/content/stock_data/2024-10-22_05-30-00.yaml
/content/stock_data/2023-11-16_05-30-00.yaml
/content/stock_data/2023-11-09_05-30-00.yaml
/content/stock_data/2024-02-29_05-30-00.yaml
/content/stock_data/2024-11-05_05-30-00.yaml
/content/stock_data/2024-09-04_05-30-00.yaml
/content/stock_data/2024-09-11_05-30-00.yaml
/content/stock_data/2023-12-06_05-30-00.yaml
/content/stock_data/2024-03-27_05-30-00.yaml
/content/stock_data/2023-12-12_05-30-00.yaml
/content/stock_data/2024-08-30_05-30-00.yaml
/content/stock_data/2024-01-15_05-30-00.yaml
/content/stock_data/2024-08-05_05-30-00.yaml
/content/stock_data/2024-10-28_05-30-00.yaml
/content/stock_data/2023-10-17_05-30-00.yaml
/content/stock_data/2024-08-16_05-30-00.yaml
/content/stock_data/2024-08-23_05-30-00.yaml
/content/stock_data/2023-12-20_05-30-00.yaml
/content/stock_data/2024-03-20_05-30-00.yaml
/content/stock_data/2024-06-21_05-30-00.yaml
/content/stock_data/2024-08-06_05-30-00.yaml
/content/stock_data/2024-01-20_05-30-00.yaml
/content/stock_data/2024-11-11_05-30-00.yaml
/content/stock_data/2024-01-09_05-30-00.yaml
/content/stock_data/2024-06-11_05-30-00.yaml
/content/stock_data/2024-07-04_05-30-00.yaml
/content/stock_data/2024-01-19_05-30-00.yaml
/content/stock_data/2024-02-01_05-30-00.yaml
/content/stock_data/2024-06-13_05-30-00.yaml
/content/stock_data/2023-12-21_05-30-00.yaml
/content/stock_data/2023-11-20_05-30-00.yaml
/content/stock_data/2023-11-01_05-30-00.yaml
/content/stock_data/2024-04-16_05-30-00.yaml
/content/stock_data/2024-03-22_05-30-00.yaml
/content/stock_data/2023-12-19_05-30-00.yaml
/content/stock_data/2024-05-24_05-30-00.yaml
/content/stock_data/2024-07-09_05-30-00.yaml
/content/stock_data/2024-10-18_05-30-00.yaml
/content/stock_data/2024-08-29_05-30-00.yaml
/content/stock_data/2024-07-31_05-30-00.yaml
/content/stock_data/2023-10-31_05-30-00.yaml
/content/stock_data/2024-10-01_05-30-00.yaml
/content/stock_data/2024-08-12_05-30-00.yaml
/content/stock_data/2024-03-13_05-30-00.yaml
/content/stock_data/2024-08-28_05-30-00.yaml
/content/stock_data/2023-10-27_05-30-00.yaml
/content/stock_data/2024-11-12_05-30-00.yaml
/content/stock_data/2023-10-19_05-30-00.yaml
/content/stock_data/2024-05-31_05-30-00.yaml
/content/stock_data/2024-02-15_05-30-00.yaml
/content/stock_data/2024-04-10_05-30-00.yaml
/content/stock_data/2024-02-27_05-30-00.yaml
/content/stock_data/2024-06-12_05-30-00.yaml
/content/stock_data/2024-10-10_05-30-00.yaml
/content/stock_data/2023-10-10_05-30-00.yaml
/content/stock_data/2024-04-25_05-30-00.yaml
/content/stock_data/2024-06-14_05-30-00.yaml
/content/stock_data/2024-05-14_05-30-00.yaml
/content/stock_data/2024-09-26_05-30-00.yaml
/content/stock_data/2024-09-03_05-30-00.yaml
/content/stock_data/2023-11-06_05-30-00.yaml
/content/stock_data/2024-07-15_05-30-00.yaml
/content/stock_data/2024-09-05_05-30-00.yaml
/content/stock_data/2024-04-23_05-30-00.yaml
/content/stock_data/2024-08-27_05-30-00.yaml
/content/stock_data/2024-07-02_05-30-00.yaml
/content/stock_data/2024-03-26_05-30-00.yaml
/content/stock_data/2024-08-07_05-30-00.yaml
/content/stock_data/2024-10-07_05-30-00.yaml
/content/stock_data/2024-06-27_05-30-00.yaml
/content/stock_data/2024-03-06_05-30-00.yaml
/content/stock_data/2024-04-09_05-30-00.yaml
/content/stock_data/2024-11-08_05-30-00.yaml
/content/stock_data/2024-05-30_05-30-00.yaml
/content/stock_data/2024-01-10_05-30-00.yaml
/content/stock_data/2023-12-04_05-30-00.yaml
/content/stock_data/2023-10-26_05-30-00.yaml
/content/stock_data/2023-12-08_05-30-00.yaml
/content/stock_data/2024-07-26_05-30-00.yaml
/content/stock_data/2024-11-13_05-30-00.yaml
/content/stock_data/2024-04-24_05-30-00.yaml
/content/stock_data/2024-09-06_05-30-00.yaml
/content/stock_data/2023-12-26_05-30-00.yaml
/content/stock_data/2024-02-02_05-30-00.yaml
/content/stock_data/2024-07-25_05-30-00.yaml
/content/stock_data/2023-11-28_05-30-00.yaml
/content/stock_data/2024-01-29_05-30-00.yaml
/content/stock_data/2023-11-08_05-30-00.yaml
/content/stock_data/2023-11-10_05-30-00.yaml
/content/stock_data/2024-06-18_05-30-00.yaml
/content/stock_data/2024-10-21_05-30-00.yaml
/content/stock_data/2024-09-19_05-30-00.yaml
/content/stock_data/2023-10-20_05-30-00.yaml
/content/stock_data/2024-09-02_05-30-00.yaml
/content/stock_data/2024-05-17_05-30-00.yaml
/content/stock_data/2024-01-01_05-30-00.yaml
/content/stock_data/2024-04-01_05-30-00.yaml
/content/stock_data/2024-07-01_05-30-00.yaml
/content/stock_data/2024-09-30_05-30-00.yaml
/content/stock_data/2024-01-08_05-30-00.yaml
/content/stock_data/2024-05-10_05-30-00.yaml
/content/stock_data/2024-11-04_05-30-00.yaml
/content/stock_data/2024-10-11_05-30-00.yaml
/content/stock_data/2024-04-19_05-30-00.yaml
/content/stock_data/2024-06-25_05-30-00.yaml
/content/stock_data/2024-06-20_05-30-00.yaml
/content/stock_data/2023-10-23_05-30-00.yaml
/content/stock_data/2024-01-11_05-30-00.yaml
/content/stock_data/2024-09-18_05-30-00.yaml
/content/stock_data/2024-09-13_05-30-00.yaml
/content/stock_data/2024-08-20_05-30-00.yaml
/content/stock_data/2024-04-18_05-30-00.yaml
/content/stock_data/2023-10-25_05-30-00.yaml
/content/stock_data/2024-08-01_05-30-00.yaml
/content/stock_data/2023-11-03_05-30-00.yaml
/content/stock_data/2024-10-16_05-30-00.yaml
/content/stock_data/2024-10-24_05-30-00.yaml
/content/stock_data/2024-05-21_05-30-00.yaml
/content/stock_data/2024-05-02_05-30-00.yaml
/content/stock_data/2023-10-16_05-30-00.yaml
/content/stock_data/2023-10-04_05-30-00.yaml
/content/stock_data/2024-03-05_05-30-00.yaml
/content/stock_data/2023-12-28_05-30-00.yaml
/content/stock_data/2024-02-12_05-30-00.yaml
/content/stock_data/2023-12-18_05-30-00.yaml
/content/stock_data/2024-05-27_05-30-00.yaml
/content/stock_data/2024-04-02_05-30-00.yaml
/content/stock_data/2024-02-26_05-30-00.yaml
/content/stock_data/2024-04-05_05-30-00.yaml
/content/stock_data/2024-11-06_05-30-00.yaml
/content/stock_data/2024-10-31_05-30-00.yaml
/content/stock_data/2024-08-13_05-30-00.yaml
/content/stock_data/2024-08-21_05-30-00.yaml
/content/stock_data/2024-11-19_05-30-00.yaml
/content/stock_data/2024-04-22_05-30-00.yaml
/content/stock_data/2024-05-15_05-30-00.yaml
/content/stock_data/2023-11-13_05-30-00.yaml
/content/stock_data/2024-07-10_05-30-00.yaml
/content/stock_data/2024-02-13_05-30-00.yaml
/content/stock_data/2024-01-16_05-30-00.yaml
/content/stock_data/2024-06-04_05-30-00.yaml
/content/stock_data/2024-10-04_05-30-00.yaml
/content/stock_data/2024-08-19_05-30-00.yaml
/content/stock_data/2024-10-25_05-30-00.yaml
/content/stock_data/2024-01-23_05-30-00.yaml
/content/stock_data/2024-07-19_05-30-00.yaml
/content/stock_data/2024-07-22_05-30-00.yaml
/content/stock_data/2023-10-03_05-30-00.yaml
/content/stock_data/2024-05-06_05-30-00.yaml
/content/stock_data/2024-01-05_05-30-00.yaml
/content/stock_data/2024-02-28_05-30-00.yaml
/content/stock_data/2024-06-05_05-30-00.yaml
/content/stock_data/2024-10-09_05-30-00.yaml
/content/stock_data/2024-03-18_05-30-00.yaml
/content/stock_data/2023-11-17_05-30-00.yaml
/content/stock_data/2024-05-28_05-30-00.yaml
/content/stock_data/2024-02-19_05-30-00.yaml
/content/stock_data/2024-04-15_05-30-00.yaml
/content/stock_data/2023-12-22_05-30-00.yaml
/content/stock_data/2024-10-23_05-30-00.yaml
/content/stock_data/2024-03-21_05-30-00.yaml
/content/stock_data/2024-09-27_05-30-00.yaml
/content/stock_data/2024-02-09_05-30-00.yaml
/content/stock_data/2023-12-13_05-30-00.yaml
/content/stock_data/2023-11-29_05-30-00.yaml
/content/stock_data/2024-10-15_05-30-00.yaml
/content/stock_data/2024-02-06_05-30-00.yaml
/content/stock_data/2024-07-08_05-30-00.yaml
/content/stock_data/2024-05-16_05-30-00.yaml
/content/stock_data/2024-02-05_05-30-00.yaml
/content/stock_data/2023-10-06_05-30-00.yaml
/content/stock_data/2024-08-08_05-30-00.yaml
/content/stock_data/2023-11-02_05-30-00.yaml
/content/stock_data/2024-03-02_05-30-00.yaml
/content/stock_data/2024-06-07_05-30-00.yaml
/content/stock_data/2024-04-12_05-30-00.yaml
/content/stock_data/2024-02-23_05-30-00.yaml
/content/stock_data/2023-11-12_05-30-00.yaml
/content/stock_data/2024-01-31_05-30-00.yaml
/content/stock_data/2024-10-03_05-30-00.yaml
/content/stock_data/2023-10-18_05-30-00.yaml
/content/stock_data/2024-07-03_05-30-00.yaml
/content/stock_data/2024-03-19_05-30-00.yaml
/content/stock_data/2024-01-03_05-30-00.yaml
/content/stock_data/2023-11-23_05-30-00.yaml
/content/stock_data/2024-05-09_05-30-00.yaml
/content/stock_data/2023-11-30_05-30-00.yaml
/content/stock_data/2024-07-11_05-30-00.yaml
/content/stock_data/2024-05-08_05-30-00.yaml
/content/stock_data/2024-05-29_05-30-00.yaml
/content/stock_data/2024-02-22_05-30-00.yaml
/content/stock_data/2024-08-22_05-30-00.yaml
/content/stock_data/2024-01-02_05-30-00.yaml
/content/stock_data/2024-08-02_05-30-00.yaml
/content/stock_data/2024-08-26_05-30-00.yaml
/content/stock_data/2024-03-07_05-30-00.yaml
/content/stock_data/2024-09-09_05-30-00.yaml
/content/stock_data/2024-11-18_05-30-00.yaml
/content/stock_data/2024-06-24_05-30-00.yaml
/content/stock_data/2024-03-28_05-30-00.yaml
/content/stock_data/2024-11-07_05-30-00.yaml
/content/stock_data/2024-10-30_05-30-00.yaml
/content/stock_data/2024-06-28_05-30-00.yaml
/content/stock_data/2023-12-11_05-30-00.yaml
/content/stock_data/2024-09-10_05-30-00.yaml
/content/stock_data/2023-12-27_05-30-00.yaml
/content/stock_data/2024-04-04_05-30-00.yaml
/content/stock_data/2024-04-08_05-30-00.yaml
/content/stock_data/2024-03-12_05-30-00.yaml
/content/stock_data/2024-11-14_05-30-00.yaml
/content/stock_data/2024-03-15_05-30-00.yaml
/content/stock_data/2024-07-30_05-30-00.yaml
/content/stock_data/2024-01-18_05-30-00.yaml
/content/stock_data/2023-10-09_05-30-00.yaml
/content/stock_data/2023-11-22_05-30-00.yaml
/content/stock_data/2024-07-24_05-30-00.yaml
/content/stock_data/2024-07-18_05-30-00.yaml
/content/stock_data/2024-07-16_05-30-00.yaml
/content/stock_data/2024-06-03_05-30-00.yaml
/content/stock_data/2024-03-04_05-30-00.yaml
/content/stock_data/2024-01-17_05-30-00.yaml
/content/stock_data/2023-10-12_05-30-00.yaml
/content/stock_data/2024-01-24_05-30-00.yaml
/content/stock_data/2024-09-25_05-30-00.yaml
/content/stock_data/2024-01-25_05-30-00.yaml
/content/stock_data/2024-11-22_05-30-00.yaml
/content/stock_data/2024-02-16_05-30-00.yaml
/content/stock_data/2024-03-11_05-30-00.yaml
/content/stock_data/2024-07-23_05-30-00.yaml
/content/stock_data/2023-12-07_05-30-00.yaml
/content/stock_data/2024-05-23_05-30-00.yaml
/content/stock_data/2024-07-29_05-30-00.yaml
/content/stock_data/2024-10-17_05-30-00.yaml
/content/stock_data/2024-09-17_05-30-00.yaml
/content/stock_data/2024-05-22_05-30-00.yaml
/content/stock_data/2024-01-30_05-30-00.yaml
/content/stock_data/2024-09-20_05-30-00.yaml
/content/stock_data/2024-05-18_05-30-00.yaml
/content/stock_data/2024-03-01_05-30-00.yaml
/content/stock_data/2024-05-13_05-30-00.yaml
/content/stock_data/2023-12-29_05-30-00.yaml
/content/stock_data/2024-10-08_05-30-00.yaml
/content/stock_data/2024-11-21_05-30-00.yaml
/content/stock_data/2024-08-09_05-30-00.yaml
/content/stock_data/2023-12-01_05-30-00.yaml
/content/stock_data/2024-07-12_05-30-00.yaml
/content/stock_data/2024-09-23_05-30-00.yaml
/content/stock_data/2024-04-30_05-30-00.yaml
/content/stock_data/2024-02-07_05-30-00.yaml
/content/stock_data/2024-09-12_05-30-00.yaml
/content/stock_data/2024-06-19_05-30-00.yaml
/content/stock_data/2024-04-03_05-30-00.yaml
/content/stock_data/2023-10-13_05-30-00.yaml
/content/stock_data/2023-12-14_05-30-00.yaml
/content/stock_data/2024-11-01_05-30-00.yaml
/content/stock_data/2024-01-04_05-30-00.yaml

In [5]:

all_dataframes = []

for filepath in yaml_files:
    with open(filepath, 'r') as file:
      content = yaml.safe_load(file)
      df = pd.DataFrame([content])

      df['source_file'] = os.path.basename(filepath)
      all_dataframes.append(df)

if all_dataframes:
    data = pd.concat(all_dataframes, ignore_index=True)
    print("DataFrame Shape:", data.shape)
else:
    print("No data found")

data.head()

DataFrame Shape: (284, 51)

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,source_file
0,"{'Ticker': 'SBIN', 'close': 845.35, 'date': '2...","{'Ticker': 'BAJFINANCE', 'close': 7158.2, 'dat...","{'Ticker': 'TITAN', 'close': 3372.75, 'date': ...","{'Ticker': 'ITC', 'close': 423.95, 'date': '20...","{'Ticker': 'TCS', 'close': 3855.85, 'date': '2...","{'Ticker': 'LT', 'close': 3602.95, 'date': '20...","{'Ticker': 'TATACONSUM', 'close': 1073.56, 'da...","{'Ticker': 'RELIANCE', 'close': 1514.03, 'date...","{'Ticker': 'HCLTECH', 'close': 1443.7, 'date':...","{'Ticker': 'JSWSTEEL', 'close': 919.2, 'date':...",...,"{'Ticker': 'CIPLA', 'close': 1479.1, 'date': '...","{'Ticker': 'BPCL', 'close': 298.4, 'date': '20...","{'Ticker': 'BRITANNIA', 'close': 5421.7, 'date...","{'Ticker': 'SBILIFE', 'close': 1450.9, 'date':...","{'Ticker': 'HINDALCO', 'close': 674.7, 'date':...","{'Ticker': 'HEROMOTOCO', 'close': 5453.0, 'dat...","{'Ticker': 'AXISBANK', 'close': 1285.4, 'date'...","{'Ticker': 'HDFCBANK', 'close': 1701.5, 'date'...","{'Ticker': 'BAJAJ-AUTO', 'close': 9474.65, 'da...",2024-06-26_05-30-00.yaml
1,"{'Ticker': 'SBIN', 'close': 561.5, 'date': '20...","{'Ticker': 'BAJFINANCE', 'close': 7103.15, 'da...","{'Ticker': 'TITAN', 'close': 3394.45, 'date': ...","{'Ticker': 'ITC', 'close': 436.25, 'date': '20...","{'Ticker': 'TCS', 'close': 3510.2, 'date': '20...","{'Ticker': 'LT', 'close': 3074.85, 'date': '20...","{'Ticker': 'TATACONSUM', 'close': 916.31, 'dat...","{'Ticker': 'RELIANCE', 'close': 1189.45, 'date...","{'Ticker': 'HCLTECH', 'close': 1326.6, 'date':...","{'Ticker': 'JSWSTEEL', 'close': 775.8, 'date':...",...,"{'Ticker': 'CIPLA', 'close': 1253.25, 'date': ...","{'Ticker': 'BPCL', 'close': 194.0, 'date': '20...","{'Ticker': 'BRITANNIA', 'close': 4699.75, 'dat...","{'Ticker': 'SBILIFE', 'close': 1423.65, 'date'...","{'Ticker': 'HINDALCO', 'close': 506.85, 'date'...","{'Ticker': 'HEROMOTOCO', 'close': 3376.5, 'dat...","{'Ticker': 'AXISBANK', 'close': 991.8, 'date':...","{'Ticker': 'HDFCBANK', 'close': 1517.95, 'date...","{'Ticker': 'BAJAJ-AUTO', 'close': 5685.95, 'da...",2023-11-21_05-30-00.yaml
2,"{'Ticker': 'SBIN', 'close': 588.35, 'date': '2...","{'Ticker': 'BAJFINANCE', 'close': 8101.95, 'da...","{'Ticker': 'TITAN', 'close': 3280.5, 'date': '...","{'Ticker': 'ITC', 'close': 448.25, 'date': '20...","{'Ticker': 'TCS', 'close': 3609.9, 'date': '20...","{'Ticker': 'LT', 'close': 3088.7, 'date': '202...","{'Ticker': 'TATACONSUM', 'close': 877.49, 'dat...","{'Ticker': 'RELIANCE', 'close': 1172.53, 'date...","{'Ticker': 'HCLTECH', 'close': 1245.6, 'date':...","{'Ticker': 'JSWSTEEL', 'close': 777.25, 'date'...",...,"{'Ticker': 'CIPLA', 'close': 1171.95, 'date': ...","{'Ticker': 'BPCL', 'close': 171.28, 'date': '2...","{'Ticker': 'BRITANNIA', 'close': 4554.95, 'dat...","{'Ticker': 'SBILIFE', 'close': 1309.35, 'date'...","{'Ticker': 'HINDALCO', 'close': 483.9, 'date':...","{'Ticker': 'HEROMOTOCO', 'close': 3100.85, 'da...","{'Ticker': 'AXISBANK', 'close': 1019.1, 'date'...","{'Ticker': 'HDFCBANK', 'close': 1539.6, 'date'...","{'Ticker': 'BAJAJ-AUTO', 'close': 5064.4, 'dat...",2023-10-11_05-30-00.yaml
3,"{'Ticker': 'SBIN', 'close': 803.0, 'date': '20...","{'Ticker': 'BAJFINANCE', 'close': 6458.5, 'dat...","{'Ticker': 'TITAN', 'close': 3402.15, 'date': ...","{'Ticker': 'ITC', 'close': 492.2, 'date': '202...","{'Ticker': 'TCS', 'close': 4295.25, 'date': '2...","{'Ticker': 'LT', 'close': 3545.2, 'date': '202...","{'Ticker': 'TATACONSUM', 'close': 1167.55, 'da...","{'Ticker': 'RELIANCE', 'close': 1461.85, 'date...","{'Ticker': 'HCLTECH', 'close': 1626.15, 'date'...","{'Ticker': 'JSWSTEEL', 'close': 890.3, 'date':...",...,"{'Ticker': 'CIPLA', 'close': 1563.8, 'date': '...","{'Ticker': 'BPCL', 'close': 325.05, 'date': '2...","{'Ticker': 'BRITANNIA', 'close': 5659.15, 'dat...","{'Ticker': 'SBILIFE', 'close': 1692.1, 'date':...","{'Ticker': 'HINDALCO', 'close': 621.45, 'date'...","{'Ticker': 'HEROMOTOCO', 'close': 5072.45, 'da...","{'Ticker': 'AXISBANK', 'close': 1153.1, 'date'...","{'Ticker': 'HDFCBANK', 'close': 1607.8, 'date'...","{'Ticker': 'BAJAJ-AUTO', 'close': 9749.6, 'dat...",2024-08-14_05-30-00.yaml
4,"{'Ticker': 'SBIN', 'close': 805.15, 'date': '2...","{'Ticker': 'BAJFINANCE', 'close': 7208.8, 'dat...","{'Ticker': 'TITAN', 'close': 3497.8, 'date': '...","{'Ticker': 'ITC', 'close': 496.95, 'date': '20...","{'Ticker': 'TCS', 'close': 4136.65, 'date': '2...","{'Ticker': 'LT', 'close': 3555.05, 'date': '20...","{'Ticker': 'TATACONSUM', 'close': 1113.55, 'da...","{'Ticker': 'RELIANCE', 'close': 1372.53, 'date...","{'Ticker': 'HCLTECH', 'close': 1855.9, 'date':...","{'Ticker': 'JSWSTEEL', 'close': 1012.5, 'date'...",...,"{'Ticker': 'CIPLA', 'close': 1598.45, 'date': ...","{'Ticker': 'BPCL', 'close': 340.75, 'date': '2...","{'Ticker': 'BRITANNIA', 'close': 5978.05, 'dat...","{'Ticker': 'SBILIFE', 'close': 1738.3, 'date':...","{'Ticker': 'HINDALCO', 'close': 743.0, 'date':...","{'Ticker': 'HEROMOTOCO', 'close': 5555.35, 'da...","{'Ticker': 'AXISBANK', 'close': 1164.35, 'date...","{'Ticker': 'HDFCBANK', 'close': 1688.1, 'date'...","{'Ticker': 'BAJAJ-AUTO', 'close': 11899.3, 'da...",2024-10-14_05-30-00.yaml

In [6]:
data.columns

Index([            0,             1,             2,             3,
                   4,             5,             6,             7,
                   8,             9,            10,            11,
                  12,            13,            14,            15,
                  16,            17,            18,            19,
                  20,            21,            22,            23,
                  24,            25,            26,            27,
                  28,            29,            30,            31,
                  32,            33,            34,            35,
                  36,            37,            38,            39,
                  40,            41,            42,            43,
                  44,            45,            46,            47,
                  48,            49, 'source_file'],
      dtype='object')

In [7]:

all_stock_data = data.iloc[:, 0:50].stack()

unique_tickers = all_stock_data.apply(lambda x: x.get('Ticker')).unique()

print(f"Unique Tickers: {list(unique_tickers)}")
print(f"Total Unique Tickers: {len(unique_tickers)}")

Unique Tickers: ['SBIN', 'BAJFINANCE', 'TITAN', 'ITC', 'TCS', 'LT', 'TATACONSUM', 'RELIANCE', 'HCLTECH', 'JSWSTEEL', 'ULTRACEMCO', 'POWERGRID', 'INFY', 'TRENT', 'BHARTIARTL', 'TATAMOTORS', 'WIPRO', 'TECHM', 'NTPC', 'HINDUNILVR', 'APOLLOHOSP', 'M&M', 'GRASIM', 'ICICIBANK', 'ADANIENT', 'ADANIPORTS', 'BEL', 'BAJAJFINSV', 'EICHERMOT', 'COALINDIA', 'MARUTI', 'INDUSINDBK', 'ASIANPAINT', 'TATASTEEL', 'HDFCLIFE', 'DRREDDY', 'SUNPHARMA', 'KOTAKBANK', 'SHRIRAMFIN', 'NESTLEIND', 'ONGC', 'CIPLA', 'BPCL', 'BRITANNIA', 'SBILIFE', 'HINDALCO', 'HEROMOTOCO', 'AXISBANK', 'HDFCBANK', 'BAJAJ-AUTO']
Total Unique Tickers: 50

In [8]:
data.columns =list(unique_tickers) + [data.columns[50]]
data.head()

,SBIN,BAJFINANCE,TITAN,ITC,TCS,LT,TATACONSUM,RELIANCE,HCLTECH,JSWSTEEL,...,CIPLA,BPCL,BRITANNIA,SBILIFE,HINDALCO,HEROMOTOCO,AXISBANK,HDFCBANK,BAJAJ-AUTO,source_file
0,"{'Ticker': 'SBIN', 'close': 845.35, 'date': '2...","{'Ticker': 'BAJFINANCE', 'close': 7158.2, 'dat...","{'Ticker': 'TITAN', 'close': 3372.75, 'date': ...","{'Ticker': 'ITC', 'close': 423.95, 'date': '20...","{'Ticker': 'TCS', 'close': 3855.85, 'date': '2...","{'Ticker': 'LT', 'close': 3602.95, 'date': '20...","{'Ticker': 'TATACONSUM', 'close': 1073.56, 'da...","{'Ticker': 'RELIANCE', 'close': 1514.03, 'date...","{'Ticker': 'HCLTECH', 'close': 1443.7, 'date':...","{'Ticker': 'JSWSTEEL', 'close': 919.2, 'date':...",...,"{'Ticker': 'CIPLA', 'close': 1479.1, 'date': '...","{'Ticker': 'BPCL', 'close': 298.4, 'date': '20...","{'Ticker': 'BRITANNIA', 'close': 5421.7, 'date...","{'Ticker': 'SBILIFE', 'close': 1450.9, 'date':...","{'Ticker': 'HINDALCO', 'close': 674.7, 'date':...","{'Ticker': 'HEROMOTOCO', 'close': 5453.0, 'dat...","{'Ticker': 'AXISBANK', 'close': 1285.4, 'date'...","{'Ticker': 'HDFCBANK', 'close': 1701.5, 'date'...","{'Ticker': 'BAJAJ-AUTO', 'close': 9474.65, 'da...",2024-06-26_05-30-00.yaml
1,"{'Ticker': 'SBIN', 'close': 561.5, 'date': '20...","{'Ticker': 'BAJFINANCE', 'close': 7103.15, 'da...","{'Ticker': 'TITAN', 'close': 3394.45, 'date': ...","{'Ticker': 'ITC', 'close': 436.25, 'date': '20...","{'Ticker': 'TCS', 'close': 3510.2, 'date': '20...","{'Ticker': 'LT', 'close': 3074.85, 'date': '20...","{'Ticker': 'TATACONSUM', 'close': 916.31, 'dat...","{'Ticker': 'RELIANCE', 'close': 1189.45, 'date...","{'Ticker': 'HCLTECH', 'close': 1326.6, 'date':...","{'Ticker': 'JSWSTEEL', 'close': 775.8, 'date':...",...,"{'Ticker': 'CIPLA', 'close': 1253.25, 'date': ...","{'Ticker': 'BPCL', 'close': 194.0, 'date': '20...","{'Ticker': 'BRITANNIA', 'close': 4699.75, 'dat...","{'Ticker': 'SBILIFE', 'close': 1423.65, 'date'...","{'Ticker': 'HINDALCO', 'close': 506.85, 'date'...","{'Ticker': 'HEROMOTOCO', 'close': 3376.5, 'dat...","{'Ticker': 'AXISBANK', 'close': 991.8, 'date':...","{'Ticker': 'HDFCBANK', 'close': 1517.95, 'date...","{'Ticker': 'BAJAJ-AUTO', 'close': 5685.95, 'da...",2023-11-21_05-30-00.yaml
2,"{'Ticker': 'SBIN', 'close': 588.35, 'date': '2...","{'Ticker': 'BAJFINANCE', 'close': 8101.95, 'da...","{'Ticker': 'TITAN', 'close': 3280.5, 'date': '...","{'Ticker': 'ITC', 'close': 448.25, 'date': '20...","{'Ticker': 'TCS', 'close': 3609.9, 'date': '20...","{'Ticker': 'LT', 'close': 3088.7, 'date': '202...","{'Ticker': 'TATACONSUM', 'close': 877.49, 'dat...","{'Ticker': 'RELIANCE', 'close': 1172.53, 'date...","{'Ticker': 'HCLTECH', 'close': 1245.6, 'date':...","{'Ticker': 'JSWSTEEL', 'close': 777.25, 'date'...",...,"{'Ticker': 'CIPLA', 'close': 1171.95, 'date': ...","{'Ticker': 'BPCL', 'close': 171.28, 'date': '2...","{'Ticker': 'BRITANNIA', 'close': 4554.95, 'dat...","{'Ticker': 'SBILIFE', 'close': 1309.35, 'date'...","{'Ticker': 'HINDALCO', 'close': 483.9, 'date':...","{'Ticker': 'HEROMOTOCO', 'close': 3100.85, 'da...","{'Ticker': 'AXISBANK', 'close': 1019.1, 'date'...","{'Ticker': 'HDFCBANK', 'close': 1539.6, 'date'...","{'Ticker': 'BAJAJ-AUTO', 'close': 5064.4, 'dat...",2023-10-11_05-30-00.yaml
3,"{'Ticker': 'SBIN', 'close': 803.0, 'date': '20...","{'Ticker': 'BAJFINANCE', 'close': 6458.5, 'dat...","{'Ticker': 'TITAN', 'close': 3402.15, 'date': ...","{'Ticker': 'ITC', 'close': 492.2, 'date': '202...","{'Ticker': 'TCS', 'close': 4295.25, 'date': '2...","{'Ticker': 'LT', 'close': 3545.2, 'date': '202...","{'Ticker': 'TATACONSUM', 'close': 1167.55, 'da...","{'Ticker': 'RELIANCE', 'close': 1461.85, 'date...","{'Ticker': 'HCLTECH', 'close': 1626.15, 'date'...","{'Ticker': 'JSWSTEEL', 'close': 890.3, 'date':...",...,"{'Ticker': 'CIPLA', 'close': 1563.8, 'date': '...","{'Ticker': 'BPCL', 'close': 325.05, 'date': '2...","{'Ticker': 'BRITANNIA', 'close': 5659.15, 'dat...","{'Ticker': 'SBILIFE', 'close': 1692.1, 'date':...","{'Ticker': 'HINDALCO', 'close': 621.45, 'date'...","{'Ticker': 'HEROMOTOCO', 'close': 5072.45, 'da...","{'Ticker': 'AXISBANK', 'close': 1153.1, 'date'...","{'Ticker': 'HDFCBANK', 'close': 1607.8, 'date'...","{'Ticker': 'BAJAJ-AUTO', 'close': 9749.6, 'dat...",2024-08-14_05-30-00.yaml
4,"{'Ticker': 'SBIN', 'close': 805.15, 'date': '2...","{'Ticker': 'BAJFINANCE', 'close': 7208.8, 'dat...","{'Ticker': 'TITAN', 'close': 3497.8, 'date': '...","{'Ticker': 'ITC', 'close': 496.95, 'date': '20...","{'Ticker': 'TCS', 'close': 4136.65, 'date': '2...","{'Ticker': 'LT', 'close': 3555.05, 'date': '20...","{'Ticker': 'TATACONSUM', 'close': 1113.55, 'da...","{'Ticker': 'RELIANCE', 'close': 1372.53, 'date...","{'Ticker': 'HCLTECH', 'close': 1855.9, 'date':...","{'Ticker': 'JSWSTEEL', 'close': 1012.5, 'date'...",...,"{'Ticker': 'CIPLA', 'close': 1598.45, 'date': ...","{'Ticker': 'BPCL', 'close': 340.75, 'date': '2...","{'Ticker': 'BRITANNIA', 'close': 5978.05, 'dat...","{'Ticker': 'SBILIFE', 'close': 1738.3, 'date':...","{'Ticker': 'HINDALCO', 'close': 743.0, 'date':...","{'Ticker': 'HEROMOTOCO', 'close': 5555.35, 'da...","{'Ticker': 'AXISBANK', 'close': 1164.35, 'date...","{'Ticker': 'HDFCBANK', 'close': 1688.1, 'date'...","{'Ticker': 'BAJAJ-AUTO', 'close': 11899.3, 'da...",2024-10-14_05-30-00.yaml

In [9]:
data.shape

(284, 51)

In [10]:
data['SBIN'].values[0]

{'Ticker': 'SBIN',
 'close': 845.35,
 'date': '2024-06-26 05:30:00',
 'high': 848.8,
 'low': 836.0,
 'month': '2024-06',
 'open': 839.85,
 'volume': 16281760}

In [11]:
split_dfs = {}

normalized_data = pd.json_normalize(all_stock_data)

for symbol, group in normalized_data.groupby('Ticker'):
    split_dfs[symbol] = group

In [12]:
split_dfs['HDFCLIFE'].reset_index(drop=True)

,Ticker,close,date,high,low,month,open,volume
0,HDFCLIFE,589.05,2024-06-26 05:30:00,599.00,587.20,2024-06,591.65,3672989
1,HDFCLIFE,667.90,2023-11-21 05:30:00,672.05,654.25,2023-11,655.00,5077816
2,HDFCLIFE,621.50,2023-10-11 05:30:00,627.00,619.00,2023-10,626.95,3102088
3,HDFCLIFE,686.35,2024-08-14 05:30:00,690.60,676.40,2024-08,686.00,2962358
4,HDFCLIFE,740.60,2024-10-14 05:30:00,741.60,726.30,2024-10,728.00,3985624
...,...,...,...,...,...,...,...,...
279,HDFCLIFE,624.10,2024-04-03 05:30:00,630.00,620.40,2024-04,629.85,3822465
280,HDFCLIFE,625.25,2023-10-13 05:30:00,633.00,614.50,2023-10,623.25,5462771
281,HDFCLIFE,684.55,2023-12-14 05:30:00,704.00,679.10,2023-12,702.00,6251731
282,HDFCLIFE,723.70,2024-11-01 05:30:00,726.00,720.15,2024-11,721.95,198743
283,HDFCLIFE,647.95,2024-01-04 05:30:00,649.00,638.00,2024-01,638.00,4412550

In [13]:
for name,df in split_dfs.items():
  print(f"{name}:{df.isnull().sum().sum()}nulls")

ADANIENT:0nulls
ADANIPORTS:0nulls
APOLLOHOSP:0nulls
ASIANPAINT:0nulls
AXISBANK:0nulls
BAJAJ-AUTO:0nulls
BAJAJFINSV:0nulls
BAJFINANCE:0nulls
BEL:0nulls
BHARTIARTL:0nulls
BPCL:0nulls
BRITANNIA:0nulls
CIPLA:0nulls
COALINDIA:0nulls
DRREDDY:0nulls
EICHERMOT:0nulls
GRASIM:0nulls
HCLTECH:0nulls
HDFCBANK:0nulls
HDFCLIFE:0nulls
HEROMOTOCO:0nulls
HINDALCO:0nulls
HINDUNILVR:0nulls
ICICIBANK:0nulls
INDUSINDBK:0nulls
INFY:0nulls
ITC:0nulls
JSWSTEEL:0nulls
KOTAKBANK:0nulls
LT:0nulls
M&M:0nulls
MARUTI:0nulls
NESTLEIND:0nulls
NTPC:0nulls
ONGC:0nulls
POWERGRID:0nulls
RELIANCE:0nulls
SBILIFE:0nulls
SBIN:0nulls
SHRIRAMFIN:0nulls
SUNPHARMA:0nulls
TATACONSUM:0nulls
TATAMOTORS:0nulls
TATASTEEL:0nulls
TCS:0nulls
TECHM:0nulls
TITAN:0nulls
TRENT:0nulls
ULTRACEMCO:0nulls
WIPRO:0nulls

In [14]:
df_list = ['SBIN', 'BAJFINANCE', 'TITAN', 'ITC', 'TCS', 'LT', 'TATACONSUM', 'RELIANCE', 'HCLTECH', 'JSWSTEEL', 'ULTRACEMCO', 'POWERGRID', 'INFY', 'TRENT', 'BHARTIARTL', 'TATAMOTORS', 'WIPRO', 'TECHM', 'NTPC', 'HINDUNILVR', 'APOLLOHOSP', 'M&M', 'GRASIM', 'ICICIBANK', 'ADANIENT', 'ADANIPORTS', 'BEL', 'BAJAJFINSV', 'EICHERMOT', 'COALINDIA', 'MARUTI', 'INDUSINDBK', 'ASIANPAINT', 'TATASTEEL', 'HDFCLIFE', 'DRREDDY', 'SUNPHARMA', 'KOTAKBANK', 'SHRIRAMFIN', 'NESTLEIND', 'ONGC', 'CIPLA', 'BPCL', 'BRITANNIA', 'SBILIFE', 'HINDALCO', 'HEROMOTOCO', 'AXISBANK', 'HDFCBANK', 'BAJAJ-AUTO']

def clean_dfs(df):

  df = df.drop_duplicates()

  df.columns = [c.lower().replace(' ', '_') for c in df.columns]

  df.ticker = df.ticker.str.lower().str.strip()

  if 'date' in df.columns:
      df['date'] = pd.to_datetime(df['date'])
      df.set_index('date', inplace=True)
      df = df.sort_index()

  return df

cleaned_dfs = {name: clean_dfs(df) for name, df in split_dfs.items()}

In [15]:
cleaned_dfs['BAJFINANCE']

,ticker,close,high,low,month,open,volume
date,,,,,,,
2023-10-03 05:30:00,bajfinance,7967.60,7975.50,7755.00,2023-10,7780.80,944555
2023-10-04 05:30:00,bajfinance,7854.05,8043.00,7820.00,2023-10,8025.00,1176384
2023-10-05 05:30:00,bajfinance,7850.90,7914.85,7826.90,2023-10,7914.85,795061
2023-10-06 05:30:00,bajfinance,8168.55,8192.00,7845.00,2023-10,7850.00,2145034
2023-10-09 05:30:00,bajfinance,8027.70,8135.00,8018.00,2023-10,8102.05,747800
...,...,...,...,...,...,...,...
2024-11-14 05:30:00,bajfinance,6549.15,6639.45,6530.00,2024-11,6572.30,527703
2024-11-18 05:30:00,bajfinance,6567.95,6657.00,6555.00,2024-11,6633.00,596535
2024-11-19 05:30:00,bajfinance,6595.30,6644.80,6561.00,2024-11,6594.35,804046
2024-11-21 05:30:00,bajfinance,6465.65,6614.00,6451.00,2024-11,6614.00,1101080
2024-11-22 05:30:00,bajfinance,6683.95,6722.40,6456.05,2024-11,6470.00,969855

In [16]:
cleaned_dfs['BAJFINANCE'].info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 284 entries, 2023-10-03 05:30:00 to 2024-11-22 05:30:00
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ticker  284 non-null    object
 1   close   284 non-null    float64
 2   high    284 non-null    float64
 3   low     284 non-null    float64
 4   month   284 non-null    object
 5   open    284 non-null    float64
 6   volume  284 non-null    int64
dtypes: float64(4), int64(1), object(2)
memory usage: 17.8+ KB

In [17]:
for name,df in cleaned_dfs.items():
  df.to_csv(f"cleaned{name}")

In [18]:
# volatility analysis

volatility_list = []

for name,df in cleaned_dfs.items():

  df['prev_close'] = df['close'].shift()
  df['daily_returns'] = (df['close'] - df['prev_close'])/ df['prev_close']

  clean_returns = df['daily_returns'].dropna()

  stock_volatility = np.std(clean_returns, ddof=1)

  volatility_list.append((name,stock_volatility))

volatility_df = pd.DataFrame(volatility_list)

In [19]:
volatility_df

             0         1
0     ADANIENT  0.028601
1   ADANIPORTS  0.026029
2   APOLLOHOSP  0.014135
3   ASIANPAINT  0.012665
4     AXISBANK  0.015625
5   BAJAJ-AUTO  0.017609
6   BAJAJFINSV  0.014118
7   BAJFINANCE  0.015918
8          BEL  0.023283
9   BHARTIARTL  0.013625
10        BPCL  0.022069
11   BRITANNIA  0.013039
12       CIPLA  0.016332
13   COALINDIA  0.021411
14     DRREDDY  0.012490
15   EICHERMOT  0.016099
16      GRASIM  0.014465
17     HCLTECH  0.014295
18    HDFCBANK  0.013490
19    HDFCLIFE  0.014630
20  HEROMOTOCO  0.016563
21    HINDALCO  0.019587
22  HINDUNILVR  0.012074
23   ICICIBANK  0.012789
24  INDUSINDBK  0.019111
25        INFY  0.014492
26         ITC  0.011944
27    JSWSTEEL  0.016384
28   KOTAKBANK  0.014216
29          LT  0.016964
30         M&M  0.019213
31      MARUTI  0.013712
32   NESTLEIND  0.012517
33        NTPC  0.019475
34        ONGC  0.022247
35   POWERGRID  0.018671
36    RELIANCE  0.013562
37     SBILIFE  0.015113
38        SBIN  0.017939
39  SHRIRAMFIN  0.021687
40   SUNPHARMA  0.011733
41  TATACONSUM  0.014805
42  TATAMOTORS  0.017877
43   TATASTEEL  0.018232
44         TCS  0.013162
45       TECHM  0.016020
46       TITAN  0.014136
47       TRENT  0.023074
48  ULTRACEMCO  0.014315
49       WIPRO  0.017468

In [20]:
volatility_df = volatility_df.rename(columns ={0:'ticker', 1:'volatility'})
sorted_vol_df = volatility_df.sort_values(by='volatility', ascending = False).head(10)
sorted_vol_df

        ticker  volatility
0     ADANIENT    0.028601
1   ADANIPORTS    0.026029
8          BEL    0.023283
47       TRENT    0.023074
34        ONGC    0.022247
10        BPCL    0.022069
39  SHRIRAMFIN    0.021687
13   COALINDIA    0.021411
21    HINDALCO    0.019587
33        NTPC    0.019475

In [21]:
Volatility = sorted_vol_df.to_csv('Volatility.csv', index = False)

In [22]:
# cumulative return over time

cumulative_returns = []

for name,df in cleaned_dfs.items():

  first_open = df['open'].iloc[0]
  last_close = df['close'].iloc[-1]

  per_diff = ((last_close - first_open)/first_open)*100

  cumulative_returns.append((name,per_diff))

cumulative_df = pd.DataFrame(cumulative_returns)

In [23]:
cumulative_df

             0           1
0     ADANIENT   -7.857734
1   ADANIPORTS   37.621065
2   APOLLOHOSP   34.951692
3   ASIANPAINT  -21.916553
4     AXISBANK   10.376812
5   BAJAJ-AUTO   87.199408
6   BAJAJFINSV    4.613625
7   BAJFINANCE  -14.096879
8          BEL  103.662074
9   BHARTIARTL   70.901171
10        BPCL   64.045911
11   BRITANNIA    7.150592
12       CIPLA   25.548986
13   COALINDIA   39.387309
14     DRREDDY    8.687286
15   EICHERMOT   45.501765
16      GRASIM   35.313935
17     HCLTECH   54.028398
18    HDFCBANK   14.315652
19    HDFCLIFE    8.471905
20  HEROMOTOCO   56.772400
21    HINDALCO   34.982405
22  HINDUNILVR   -1.797189
23   ICICIBANK   34.305380
24  INDUSINDBK  -30.293296
25        INFY   32.464051
26         ITC    7.630385
27    JSWSTEEL   25.857961
28   KOTAKBANK    1.817919
29          LT   18.516691
30         M&M   88.639494
31      MARUTI    3.303516
32   NESTLEIND   -0.150620
33        NTPC   49.560057
34        ONGC   29.741152
35   POWERGRID   69.534591
36    RELIANCE    8.620823
37     SBILIFE   14.053680
38        SBIN   36.783439
39  SHRIRAMFIN   47.061404
40   SUNPHARMA   54.827304
41  TATACONSUM    9.993949
42  TATAMOTORS   25.039519
43   TATASTEEL   10.682171
44         TCS   20.100730
45       TECHM   43.163198
46       TITAN    5.078125
47       TRENT  220.725064
48  ULTRACEMCO   37.233683
49       WIPRO   40.644606

In [24]:
cumulative_df = cumulative_df.rename(columns ={0:'ticker', 1:'cum_percentage'})
sorted_cum_df = cumulative_df.sort_values(by='cum_percentage', ascending = False).head(5)
sorted_cum_df

        ticker  cum_percentage
47       TRENT      220.725064
8          BEL      103.662074
30         M&M       88.639494
5   BAJAJ-AUTO       87.199408
9   BHARTIARTL       70.901171

In [25]:
Cumulative_percentage = sorted_cum_df.to_csv('Cumulative_percentage.csv', index = False)

In [26]:
sector_df = pd.read_csv('/content/Sector_data - Sheet1.csv')

In [27]:
#calculate sector wise performance

sector_df

                COMPANY           sector                          Symbol
0     ADANI ENTERPRISES    MISCELLANEOUS   ADANI ENTERPRISES: ADANIGREEN
1     ADANI PORTS & SEZ    MISCELLANEOUS   ADANI PORTS & SEZ: ADANIPORTS
2      APOLLO HOSPITALS    MISCELLANEOUS    APOLLO HOSPITALS: APOLLOHOSP
3          ASIAN PAINTS           PAINTS        ASIAN PAINTS: ASIANPAINT
4             AXIS BANK          BANKING             AXIS BANK: AXISBANK
5            BAJAJ AUTO      AUTOMOBILES          BAJAJ AUTO: BAJAJ-AUTO
6         BAJAJ FINANCE          FINANCE       BAJAJ FINANCE: BAJFINANCE
7         BAJAJ FINSERV          FINANCE       BAJAJ FINSERV: BAJAJFINSV
8    BHARAT ELECTRONICS          DEFENCE         BHARAT ELECTRONICS: BEL
9         BHARTI AIRTEL          TELECOM           BHARTI AIRTEL: AIRTEL
10                 BPCL           ENERGY                      BPCL: BPCL
11                CIPLA  PHARMACEUTICALS                    CIPLA: CIPLA
12           COAL INDIA           MINING           COAL INDIA: COALINDIA
13       DR. REDDYS LAB  PHARMACEUTICALS         DR. REDDYS LAB: DRREDDY
14        EICHER MOTORS      AUTOMOBILES        EICHER MOTORS: EICHERMOT
15               GRASIM         TEXTILES                  GRASIM: GRASIM
16     HCL TECHNOLOGIES         SOFTWARE       HCL TECHNOLOGIES: HCLTECH
17            HDFC BANK          BANKING             HDFC BANK: HDFCBANK
18  HDFC LIFE INSURANCE        INSURANCE   HDFC LIFE INSURANCE: HDFCLIFE
19        HERO MOTOCORP      AUTOMOBILES       HERO MOTOCORP: HEROMOTOCO
20             HINDALCO        ALUMINIUM              HINDALCO: HINDALCO
21   HINDUSTAN UNILEVER             FMCG  HINDUSTAN UNILEVER: HINDUNILVR
22           ICICI BANK          BANKING           ICICI BANK: ICICIBANK
23        INDUSIND BANK          BANKING       INDUSIND BANK: INDUSINDBK
24              INFOSYS         SOFTWARE                   INFOSYS: INFY
25                  IOC           ENERGY                        IOC: IOC
26                  ITC   FOOD & TOBACCO                        ITC: ITC
27            JSW STEEL            STEEL             JSW STEEL: JSWSTEEL
28  KOTAK MAHINDRA BANK          BANKING  KOTAK MAHINDRA BANK: KOTAKBANK
29                  L&T      ENGINEERING                         L&T: LT
30                  M&M      AUTOMOBILES                        M&M: M&M
31        MARUTI SUZUKI      AUTOMOBILES           MARUTI SUZUKI: MARUTI
32               NESTLE   FOOD & TOBACCO               NESTLE: NESTLEIND
33                 NTPC            POWER                      NTPC: NTPC
34                 ONGC           ENERGY                      ONGC: ONGC
35           POWER GRID            POWER           POWER GRID: POWERGRID
36        RELIANCE IND.           ENERGY         RELIANCE IND.: RELIANCE
37                  SBI          BANKING                       SBI: SBIN
38   SBI LIFE INSURANCE        INSURANCE     SBI LIFE INSURANCE: SBILIFE
39      SHRIRAM FINANCE          FINANCE     SHRIRAM FINANCE: SHRIRAMFIN
40           SUN PHARMA  PHARMACEUTICALS           SUN PHARMA: SUNPHARMA
41        TATA CONSUMER             FMCG     TATA CONSUMER: TATACONSUMER
42          TATA MOTORS      AUTOMOBILES         TATA MOTORS: TATAMOTORS
43           TATA STEEL            STEEL           TATA STEEL: TATASTEEL
44                  TCS         SOFTWARE                        TCS: TCS
45        TECH MAHINDRA         SOFTWARE            TECH MAHINDRA: TECHM
46                TITAN        RETAILING                    TITAN: TITAN
47                TRENT        RETAILING                    TRENT: TRENT
48     ULTRATECH CEMENT           CEMENT    ULTRATECH CEMENT: ULTRACEMCO
49                WIPRO         SOFTWARE                    WIPRO: WIPRO

In [28]:
sector_df.shape

(50, 3)

In [29]:
sector_df['ticker'] = sector_df['Symbol'].str.split(":").str[-1].str.strip()
sector_df.loc[sector_df['COMPANY'] == 'ADANI ENTERPRISES', 'ticker'] = 'ADANIENT'
sector_df.loc[sector_df['COMPANY'] == 'BHARTI AIRTEL', 'ticker'] = 'BHARTIARTL'
sector_df.loc[sector_df['COMPANY'] == 'TATA CONSUMER', 'ticker'] = 'TATACONSUM'
sector_df

,COMPANY,sector,Symbol,ticker
0,ADANI ENTERPRISES,MISCELLANEOUS,ADANI ENTERPRISES: ADANIGREEN,ADANIENT
1,ADANI PORTS & SEZ,MISCELLANEOUS,ADANI PORTS & SEZ: ADANIPORTS,ADANIPORTS
2,APOLLO HOSPITALS,MISCELLANEOUS,APOLLO HOSPITALS: APOLLOHOSP,APOLLOHOSP
3,ASIAN PAINTS,PAINTS,ASIAN PAINTS: ASIANPAINT,ASIANPAINT
4,AXIS BANK,BANKING,AXIS BANK: AXISBANK,AXISBANK
5,BAJAJ AUTO,AUTOMOBILES,BAJAJ AUTO: BAJAJ-AUTO,BAJAJ-AUTO
6,BAJAJ FINANCE,FINANCE,BAJAJ FINANCE: BAJFINANCE,BAJFINANCE
7,BAJAJ FINSERV,FINANCE,BAJAJ FINSERV: BAJAJFINSV,BAJAJFINSV
8,BHARAT ELECTRONICS,DEFENCE,BHARAT ELECTRONICS: BEL,BEL
9,BHARTI AIRTEL,TELECOM,BHARTI AIRTEL: AIRTEL,BHARTIARTL
10,BPCL,ENERGY,BPCL: BPCL,BPCL
11,CIPLA,PHARMACEUTICALS,CIPLA: CIPLA,CIPLA
12,COAL INDIA,MINING,COAL INDIA: COALINDIA,COALINDIA
13,DR. REDDYS LAB,PHARMACEUTICALS,DR. REDDYS LAB: DRREDDY,DRREDDY
14,EICHER MOTORS,AUTOMOBILES,EICHER MOTORS: EICHERMOT,EICHERMOT
15,GRASIM,TEXTILES,GRASIM: GRASIM,GRASIM
16,HCL TECHNOLOGIES,SOFTWARE,HCL TECHNOLOGIES: HCLTECH,HCLTECH
17,HDFC BANK,BANKING,HDFC BANK: HDFCBANK,HDFCBANK
18,HDFC LIFE INSURANCE,INSURANCE,HDFC LIFE INSURANCE: HDFCLIFE,HDFCLIFE
19,HERO MOTOCORP,AUTOMOBILES,HERO MOTOCORP: HEROMOTOCO,HEROMOTOCO
20,HINDALCO,ALUMINIUM,HINDALCO: HINDALCO,HINDALCO
21,HINDUSTAN UNILEVER,FMCG,HINDUSTAN UNILEVER: HINDUNILVR,HINDUNILVR
22,ICICI BANK,BANKING,ICICI BANK: ICICIBANK,ICICIBANK
23,INDUSIND BANK,BANKING,INDUSIND BANK: INDUSINDBK,INDUSINDBK
24,INFOSYS,SOFTWARE,INFOSYS: INFY,INFY
25,IOC,ENERGY,IOC: IOC,IOC
26,ITC,FOOD & TOBACCO,ITC: ITC,ITC
27,JSW STEEL,STEEL,JSW STEEL: JSWSTEEL,JSWSTEEL
28,KOTAK MAHINDRA BANK,BANKING,KOTAK MAHINDRA BANK: KOTAKBANK,KOTAKBANK
29,L&T,ENGINEERING,L&T: LT,LT
30,M&M,AUTOMOBILES,M&M: M&M,M&M
31,MARUTI SUZUKI,AUTOMOBILES,MARUTI SUZUKI: MARUTI,MARUTI
32,NESTLE,FOOD & TOBACCO,NESTLE: NESTLEIND,NESTLEIND
33,NTPC,POWER,NTPC: NTPC,NTPC
34,ONGC,ENERGY,ONGC: ONGC,ONGC
35,POWER GRID,POWER,POWER GRID: POWERGRID,POWERGRID
36,RELIANCE IND.,ENERGY,RELIANCE IND.: RELIANCE,RELIANCE
37,SBI,BANKING,SBI: SBIN,SBIN
38,SBI LIFE INSURANCE,INSURANCE,SBI LIFE INSURANCE: SBILIFE,SBILIFE
39,SHRIRAM FINANCE,FINANCE,SHRIRAM FINANCE: SHRIRAMFIN,SHRIRAMFIN
40,SUN PHARMA,PHARMACEUTICALS,SUN PHARMA: SUNPHARMA,SUNPHARMA
41,TATA CONSUMER,FMCG,TATA CONSUMER: TATACONSUMER,TATACONSUM
42,TATA MOTORS,AUTOMOBILES,TATA MOTORS: TATAMOTORS,TATAMOTORS
43,TATA STEEL,STEEL,TATA STEEL: TATASTEEL,TATASTEEL
44,TCS,SOFTWARE,TCS: TCS,TCS
45,TECH MAHINDRA,SOFTWARE,TECH MAHINDRA: TECHM,TECHM
46,TITAN,RETAILING,TITAN: TITAN,TITAN
47,TRENT,RETAILING,TRENT: TRENT,TRENT
48,ULTRATECH CEMENT,CEMENT,ULTRATECH CEMENT: ULTRACEMCO,ULTRACEMCO
49,WIPRO,SOFTWARE,WIPRO: WIPRO,WIPRO

In [30]:
modsector_df = pd.merge(
    cumulative_df,
    sector_df,
    on = "ticker",
    how = "inner"
)

In [31]:
modsector_df

,ticker,cum_percentage,COMPANY,sector,Symbol
0,ADANIENT,-7.857734,ADANI ENTERPRISES,MISCELLANEOUS,ADANI ENTERPRISES: ADANIGREEN
1,ADANIPORTS,37.621065,ADANI PORTS & SEZ,MISCELLANEOUS,ADANI PORTS & SEZ: ADANIPORTS
2,APOLLOHOSP,34.951692,APOLLO HOSPITALS,MISCELLANEOUS,APOLLO HOSPITALS: APOLLOHOSP
3,ASIANPAINT,-21.916553,ASIAN PAINTS,PAINTS,ASIAN PAINTS: ASIANPAINT
4,AXISBANK,10.376812,AXIS BANK,BANKING,AXIS BANK: AXISBANK
5,BAJAJ-AUTO,87.199408,BAJAJ AUTO,AUTOMOBILES,BAJAJ AUTO: BAJAJ-AUTO
6,BAJAJFINSV,4.613625,BAJAJ FINSERV,FINANCE,BAJAJ FINSERV: BAJAJFINSV
7,BAJFINANCE,-14.096879,BAJAJ FINANCE,FINANCE,BAJAJ FINANCE: BAJFINANCE
8,BEL,103.662074,BHARAT ELECTRONICS,DEFENCE,BHARAT ELECTRONICS: BEL
9,BHARTIARTL,70.901171,BHARTI AIRTEL,TELECOM,BHARTI AIRTEL: AIRTEL
10,BPCL,64.045911,BPCL,ENERGY,BPCL: BPCL
11,CIPLA,25.548986,CIPLA,PHARMACEUTICALS,CIPLA: CIPLA
12,COALINDIA,39.387309,COAL INDIA,MINING,COAL INDIA: COALINDIA
13,DRREDDY,8.687286,DR. REDDYS LAB,PHARMACEUTICALS,DR. REDDYS LAB: DRREDDY
14,EICHERMOT,45.501765,EICHER MOTORS,AUTOMOBILES,EICHER MOTORS: EICHERMOT
15,GRASIM,35.313935,GRASIM,TEXTILES,GRASIM: GRASIM
16,HCLTECH,54.028398,HCL TECHNOLOGIES,SOFTWARE,HCL TECHNOLOGIES: HCLTECH
17,HDFCBANK,14.315652,HDFC BANK,BANKING,HDFC BANK: HDFCBANK
18,HDFCLIFE,8.471905,HDFC LIFE INSURANCE,INSURANCE,HDFC LIFE INSURANCE: HDFCLIFE
19,HEROMOTOCO,56.772400,HERO MOTOCORP,AUTOMOBILES,HERO MOTOCORP: HEROMOTOCO
20,HINDALCO,34.982405,HINDALCO,ALUMINIUM,HINDALCO: HINDALCO
21,HINDUNILVR,-1.797189,HINDUSTAN UNILEVER,FMCG,HINDUSTAN UNILEVER: HINDUNILVR
22,ICICIBANK,34.305380,ICICI BANK,BANKING,ICICI BANK: ICICIBANK
23,INDUSINDBK,-30.293296,INDUSIND BANK,BANKING,INDUSIND BANK: INDUSINDBK
24,INFY,32.464051,INFOSYS,SOFTWARE,INFOSYS: INFY
25,ITC,7.630385,ITC,FOOD & TOBACCO,ITC: ITC
26,JSWSTEEL,25.857961,JSW STEEL,STEEL,JSW STEEL: JSWSTEEL
27,KOTAKBANK,1.817919,KOTAK MAHINDRA BANK,BANKING,KOTAK MAHINDRA BANK: KOTAKBANK
28,LT,18.516691,L&T,ENGINEERING,L&T: LT
29,M&M,88.639494,M&M,AUTOMOBILES,M&M: M&M
30,MARUTI,3.303516,MARUTI SUZUKI,AUTOMOBILES,MARUTI SUZUKI: MARUTI
31,NESTLEIND,-0.150620,NESTLE,FOOD & TOBACCO,NESTLE: NESTLEIND
32,NTPC,49.560057,NTPC,POWER,NTPC: NTPC
33,ONGC,29.741152,ONGC,ENERGY,ONGC: ONGC
34,POWERGRID,69.534591,POWER GRID,POWER,POWER GRID: POWERGRID
35,RELIANCE,8.620823,RELIANCE IND.,ENERGY,RELIANCE IND.: RELIANCE
36,SBILIFE,14.053680,SBI LIFE INSURANCE,INSURANCE,SBI LIFE INSURANCE: SBILIFE
37,SBIN,36.783439,SBI,BANKING,SBI: SBIN
38,SHRIRAMFIN,47.061404,SHRIRAM FINANCE,FINANCE,SHRIRAM FINANCE: SHRIRAMFIN
39,SUNPHARMA,54.827304,SUN PHARMA,PHARMACEUTICALS,SUN PHARMA: SUNPHARMA
40,TATACONSUM,9.993949,TATA CONSUMER,FMCG,TATA CONSUMER: TATACONSUMER
41,TATAMOTORS,25.039519,TATA MOTORS,AUTOMOBILES,TATA MOTORS: TATAMOTORS
42,TATASTEEL,10.682171,TATA STEEL,STEEL,TATA STEEL: TATASTEEL
43,TCS,20.100730,TCS,SOFTWARE,TCS: TCS
44,TECHM,43.163198,TECH MAHINDRA,SOFTWARE,TECH MAHINDRA: TECHM
45,TITAN,5.078125,TITAN,RETAILING,TITAN: TITAN
46,TRENT,220.725064,TRENT,RETAILING,TRENT: TRENT
47,ULTRACEMCO,37.233683,ULTRATECH CEMENT,CEMENT,ULTRATECH CEMENT: ULTRACEMCO
48,WIPRO,40.644606,WIPRO,SOFTWARE,WIPRO: WIPRO

In [32]:
modsector_df.shape

(49, 5)

In [33]:
sectorprfm_df = modsector_df.groupby('sector')['cum_percentage'].mean().reset_index()
sectorprfm_df

             sector  cum_percentage
0         ALUMINIUM       34.982405
1       AUTOMOBILES       51.076017
2           BANKING       11.217651
3            CEMENT       37.233683
4           DEFENCE      103.662074
5            ENERGY       34.135962
6       ENGINEERING       18.516691
7           FINANCE       12.526050
8              FMCG        4.098380
9    FOOD & TOBACCO        3.739883
10        INSURANCE       11.262793
11           MINING       39.387309
12    MISCELLANEOUS       21.571675
13           PAINTS      -21.916553
14  PHARMACEUTICALS       29.687859
15            POWER       59.547324
16        RETAILING      112.901594
17         SOFTWARE       38.080196
18            STEEL       18.270066
19          TELECOM       70.901171
20         TEXTILES       35.313935

In [34]:
Sector_performance = sectorprfm_df.to_csv('Sector_performance.csv', index = False)

In [35]:
#stock price correlation

all_daily_returns = pd.DataFrame({
    name: stock_df['daily_returns'] for name, stock_df in cleaned_dfs.items()
})

corr_df = all_daily_returns.corr()
corr_df

,ADANIENT,ADANIPORTS,APOLLOHOSP,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJAJFINSV,BAJFINANCE,BEL,BHARTIARTL,...,SUNPHARMA,TATACONSUM,TATAMOTORS,TATASTEEL,TCS,TECHM,TITAN,TRENT,ULTRACEMCO,WIPRO
ADANIENT,1.000000,0.874233,0.136501,0.291583,0.297736,0.201871,0.356547,0.336031,0.522680,0.282859,...,0.166256,0.203847,0.324071,0.423563,0.115790,0.141677,0.283281,0.190412,0.361152,0.224003
ADANIPORTS,0.874233,1.000000,0.168902,0.274045,0.380514,0.204456,0.398041,0.398769,0.585672,0.316537,...,0.215856,0.220655,0.339241,0.466043,0.132423,0.148034,0.296148,0.201076,0.402489,0.238986
APOLLOHOSP,0.136501,0.168902,1.000000,0.258055,0.179381,0.223900,0.249392,0.223142,0.224594,0.236810,...,0.286227,0.096700,0.212357,0.254731,0.106846,0.169118,0.253361,0.089516,0.272951,0.223738
ASIANPAINT,0.291583,0.274045,0.258055,1.000000,0.126055,0.167650,0.248090,0.296922,0.156953,0.146953,...,0.202262,0.244278,0.105847,0.287050,0.166699,0.162959,0.307404,0.223094,0.280647,0.140642
AXISBANK,0.297736,0.380514,0.179381,0.126055,1.000000,0.198477,0.393683,0.354079,0.330512,0.238602,...,0.143991,0.139747,0.232145,0.370957,0.094669,0.136469,0.145931,0.199748,0.397024,0.207802
BAJAJ-AUTO,0.201871,0.204456,0.223900,0.167650,0.198477,1.000000,0.237654,0.178554,0.233430,0.262054,...,0.149957,0.185135,0.294698,0.283691,0.017591,0.037877,0.201060,0.223399,0.263342,0.102492
BAJAJFINSV,0.356547,0.398041,0.249392,0.248090,0.393683,0.237654,1.000000,0.748723,0.346261,0.257664,...,0.213243,0.304497,0.280169,0.456570,0.234842,0.204276,0.329527,0.201133,0.463107,0.306650
BAJFINANCE,0.336031,0.398769,0.223142,0.296922,0.354079,0.178554,0.748723,1.000000,0.315822,0.291641,...,0.137262,0.236369,0.212748,0.381616,0.174425,0.173360,0.269039,0.229188,0.434558,0.238516
BEL,0.522680,0.585672,0.224594,0.156953,0.330512,0.233430,0.346261,0.315822,1.000000,0.309294,...,0.163531,0.175809,0.367173,0.520365,0.120758,0.222395,0.166767,0.263415,0.435501,0.255854
BHARTIARTL,0.282859,0.316537,0.236810,0.146953,0.238602,0.262054,0.257664,0.291641,0.309294,1.000000,...,0.272227,0.248732,0.269331,0.305352,0.193183,0.272352,0.276037,0.247927,0.354121,0.259131
BPCL,0.455289,0.495117,0.174973,0.215787,0.222936,0.215531,0.345286,0.272608,0.505802,0.265020,...,0.205494,0.156373,0.415679,0.462885,0.175426,0.201632,0.275086,0.212755,0.401651,0.211945
BRITANNIA,0.130655,0.133400,0.231736,0.426896,0.130775,0.094707,0.225478,0.207936,0.073187,0.121226,...,0.187936,0.405008,0.109019,0.118834,0.117657,0.129664,0.073109,0.034251,0.181814,0.169110
CIPLA,0.094238,0.091118,0.231114,0.147018,0.085260,0.043536,0.135928,0.053728,0.082404,0.119963,...,0.414759,0.073227,0.068966,0.131112,0.079022,0.052199,0.107529,0.136473,0.133328,0.087595
COALINDIA,0.494534,0.546202,0.243537,0.194986,0.332553,0.225770,0.279739,0.280246,0.620262,0.267037,...,0.177471,0.213072,0.406315,0.535425,0.095263,0.178173,0.238336,0.254629,0.321221,0.235794
DRREDDY,0.164552,0.160972,0.235448,0.149961,0.091461,0.104890,0.257756,0.088308,0.131475,0.178094,...,0.396686,0.110615,0.200125,0.207222,0.223212,0.220019,0.139991,0.168870,0.251558,0.279839
EICHERMOT,0.331647,0.269610,0.290339,0.257914,0.286161,0.276130,0.241356,0.189578,0.284223,0.294734,...,0.175283,0.172375,0.316620,0.314499,0.143776,0.189578,0.268206,0.234639,0.304244,0.262235
GRASIM,0.344468,0.356102,0.258184,0.344453,0.367053,0.200661,0.435099,0.368980,0.337925,0.297192,...,0.218122,0.282995,0.336304,0.463646,0.179943,0.175110,0.368297,0.241469,0.590116,0.245002
HCLTECH,0.139916,0.152640,0.279181,0.117484,0.107496,0.124516,0.267826,0.183187,0.224041,0.258437,...,0.156099,0.209540,0.269334,0.268719,0.629079,0.548280,0.199441,0.207422,0.205442,0.580667
HDFCBANK,0.338118,0.375305,0.110238,0.264323,0.424931,0.182233,0.318705,0.331632,0.330752,0.211028,...,0.071820,0.108654,0.204986,0.380764,0.045286,0.204667,0.188021,0.102739,0.360209,0.193599
HDFCLIFE,0.216839,0.247059,0.141669,0.206022,0.251479,0.191902,0.347351,0.307101,0.251302,0.215032,...,0.168518,0.214307,0.224166,0.275177,0.115449,0.119529,0.226622,0.202129,0.241819,0.194261
HEROMOTOCO,0.208576,0.202512,0.248153,0.180187,0.172582,0.406801,0.236211,0.171239,0.087771,0.183911,...,0.220462,0.212351,0.290746,0.287774,0.108665,0.111243,0.302480,0.218545,0.295383,0.204583
HINDALCO,0.304966,0.337762,0.062547,0.212252,0.227375,0.216860,0.296242,0.254539,0.375871,0.294149,...,0.254427,0.180976,0.364959,0.630099,0.161044,0.236387,0.249438,0.268630,0.313590,0.262244
HINDUNILVR,-0.000796,0.002376,0.107865,0.269889,0.009843,0.124955,0.139454,0.127433,-0.058291,0.158531,...,0.051338,0.412071,0.088024,0.084734,0.145345,0.131313,0.187477,0.083964,0.165126,0.185425
ICICIBANK,0.394584,0.442289,0.164303,0.158839,0.636786,0.108522,0.415419,0.350008,0.313735,0.366610,...,0.202726,0.120592,0.199674,0.345279,0.166489,0.168655,0.146474,0.121659,0.430208,0.221655
INDUSINDBK,0.391347,0.422431,0.129152,0.180855,0.339661,0.206118,0.422960,0.406266,0.308607,0.231639,...,0.122917,0.273550,0.333359,0.396258,0.085590,0.103153,0.240433,0.199126,0.345066,0.186573
INFY,0.115149,0.149400,0.121671,0.104310,0.086467,-0.003487,0.241348,0.197446,0.164705,0.288846,...,0.143073,0.245193,0.181710,0.180954,0.707884,0.649146,0.215072,0.150991,0.224565,0.571208
ITC,0.245803,0.273774,0.174046,0.275550,0.275001,0.140413,0.303636,0.304404,0.230195,0.260515,...,0.186995,0.302655,0.188564,0.257269,0.152274,0.217816,0.318261,0.151491,0.260144,0.233139
JSWSTEEL,0.405664,0.434606,0.276060,0.333566,0.365966,0.223461,0.447526,0.390934,0.458783,0.364830,...,0.252222,0.235532,0.408712,0.794189,0.209291,0.268989,0.322128,0.256977,0.546643,0.360374
KOTAKBANK,0.243752,0.305838,0.139795,0.181202,0.292039,0.082628,0.273104,0.315904,0.266514,0.318991,...,0.089100,0.197429,0.160206,0.262726,0.115565,0.174738,0.168053,0.081005,0.334770,0.245812
LT,0.483136,0.513974,0.235883,0.223101,0.352081,0.175763,0.398992,0.378919,0.591401,0.323943,...,0.167209,0.168087,0.352993,0.483848,0.217062,0.210315,0.231900,0.185279,0.473174,0.319899
M&M,0.304545,0.319381,0.251029,0.140121,0.235556,0.271628,0.337684,0.267973,0.369498,0.291923,...,0.285570,0.169598,0.400987,0.427432,0.174295,0.219419,0.285280,0.249013,0.418644,0.299971
MARUTI,0.315659,0.302342,0.194062,0.260366,0.260371,0.342005,0.329276,0.281244,0.224642,0.348079,...,0.200872,0.207816,0.405831,0.395828,0.164892,0.147973,0.332279,0.183321,0.349174,0.205206
NESTLEIND,0.115017,0.087843,0.224446,0.282631,0.100344,0.179005,0.273745,0.246975,0.065317,0.106086,...,0.141183,0.375731,0.147040,0.103308,0.114495,0.054905,0.236875,0.136674,0.278184,0.149708
NTPC,0.545960,0.610464,0.194129,0.222064,0.394813,0.202560,0.391226,0.328260,0.607886,0.366187,...,0.230246,0.187078,0.409924,0.533943,0.109945,0.189870,0.334051,0.235736,0.448524,0.202935
ONGC,0.484910,0.521803,0.173658,0.128654,0.313449,0.187871,0.305737,0.316297,0.572377,0.346411,...,0.228145,0.177229,0.436927,0.491860,0.168162,0.233515,0.192695,0.211585,0.404519,0.288967
POWERGRID,0.403946,0.511696,0.178438,0.111665,0.294693,0.168364,0.307034,0.245101,0.544756,0.311228,...,0.246122,0.150893,0.355057,0.502428,0.097295,0.151609,0.208609,0.200542,0.396684,0.166631
RELIANCE,0.487097,0.512736,0.234728,0.294963,0.423456,0.246961,0.407201,0.413342,0.492507,0.365995,...,0.293116,0.207763,0.386583,0.441104,0.247971,0.266063,0.329323,0.282779,0.490382,0.364313
SBILIFE,0.289193,0.284613,0.160706,0.220352,0.183053,0.190211,0.405717,0.335101,0.209939,0.241723,...,0.131142,0.210613,0.224283,0.232113,0.175014,0.154585,0.219543,0.170800,0.266797,0.246338
SBIN,0.544697,0.579516,0.182850,0.107866,0.516122,0.154854,0.419859,0.397696,0.580213,0.290364,...,0.122857,0.117567,0.363321,0.489624,0.162862,0.193755,0.223221,0.276491,0.425494,0.243531
SHRIRAMFIN,0.410298,0.469890,0.291768,0.202540,0.448564,0.301142,0.468791,0.461618,0.475480,0.360799,...,0.210963,0.187778,0.362474,0.436920,0.113654,0.227147,0.254687,0.228691,0.468239,0.298607
SUNPHARMA,0.166256,0.215856,0.286227,0.202262,0.143991,0.149957,0.213243,0.137262,0.163531,0.272227,...,1.000000,0.172295,0.305911,0.260971,0.147690,0.164001,0.214335,0.256380,0.232441,0.192644
TATACONSUM,0.203847,0.220655,0.096700,0.244278,0.139747,0.185135,0.304497,0.236369,0.175809,0.248732,...,0.172295,1.000000,0.188062,0.225777,0.271634,0.212756,0.311262,0.185995,0.244972,0.249107
TATAMOTORS,0.324071,0.339241,0.212357,0.105847,0.232145,0.294698,0.280169,0.212748,0.367173,0.269331,...,0.305911,0.188062,1.000000,0.513416,0.248889,0.279026,0.274323,0.222437,0.353946,0.311797
TATASTEEL,0.423563,0.466043,0.254731,0.287050,0.370957,0.283691,0.456570,0.381616,0.520365,0.305352,...,0.260971,0.225777,0.513416,1.000000,0.235867,0.283648,0.293416,0.218748,0.471722,0.331808
TCS,0.115790,0.132423,0.106846,0.166699,0.094669,0.017591,0.234842,0.174425,0.120758,0.193183,...,0.147690,0.271634,0.248889,0.235867,1.000000,0.578882,0.145475,0.122021,0.238679,0.591427
TECHM,0.141677,0.148034,0.169118,0.162959,0.136469,0.037877,0.204276,0.173360,0.222395,0.272352,...,0.164001,0.212756,0.279026,0.283648,0.578882,1.000000,0.243389,0.150751,0.269904,0.599253
TITAN,0.283281,0.296148,0.253361,0.307404,0.145931,0.201060,0.329527,0.269039,0.166767,0.276037,...,0.214335,0.311262,0.274323,0.293416,0.145475,0.243389,1.000000,0.194346,0.353920,0.259623
TRENT,0.190412,0.201076,0.089516,0.223094,0.199748,0.223399,0.201133,0.229188,0.263415,0.247927,...,0.256380,0.185995,0.222437,0.218748,0.122021,0.150751,0.194346,1.000000,0.295226,0.150452
ULTRACEMCO,0.361152,0.402489,0.272951,0.280647,0.397024,0.263342,0.463107,0.434558,0.435501,0.354121,...,0.232441,0.244972,0.353946,0.471722,0.238679,0.269904,0.353920,0.295226,1.000000,0.291504
WIPRO,0.224003,0.238986,0.223738,0.140642,0.207802,0.102492,0.306650,0.238516,0.255854,0.259131,...,0.192644,0.249107,0.311797,0.331808,0.591427,0.599253,0.259623,0.150452,0.291504,1.000000

In [36]:
corr_df = corr_df.reset_index().rename(columns={'index': 'Tickers'})

In [37]:
corr_df

,Tickers,ADANIENT,ADANIPORTS,APOLLOHOSP,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJAJFINSV,BAJFINANCE,BEL,...,SUNPHARMA,TATACONSUM,TATAMOTORS,TATASTEEL,TCS,TECHM,TITAN,TRENT,ULTRACEMCO,WIPRO
0,ADANIENT,1.000000,0.874233,0.136501,0.291583,0.297736,0.201871,0.356547,0.336031,0.522680,...,0.166256,0.203847,0.324071,0.423563,0.115790,0.141677,0.283281,0.190412,0.361152,0.224003
1,ADANIPORTS,0.874233,1.000000,0.168902,0.274045,0.380514,0.204456,0.398041,0.398769,0.585672,...,0.215856,0.220655,0.339241,0.466043,0.132423,0.148034,0.296148,0.201076,0.402489,0.238986
2,APOLLOHOSP,0.136501,0.168902,1.000000,0.258055,0.179381,0.223900,0.249392,0.223142,0.224594,...,0.286227,0.096700,0.212357,0.254731,0.106846,0.169118,0.253361,0.089516,0.272951,0.223738
3,ASIANPAINT,0.291583,0.274045,0.258055,1.000000,0.126055,0.167650,0.248090,0.296922,0.156953,...,0.202262,0.244278,0.105847,0.287050,0.166699,0.162959,0.307404,0.223094,0.280647,0.140642
4,AXISBANK,0.297736,0.380514,0.179381,0.126055,1.000000,0.198477,0.393683,0.354079,0.330512,...,0.143991,0.139747,0.232145,0.370957,0.094669,0.136469,0.145931,0.199748,0.397024,0.207802
5,BAJAJ-AUTO,0.201871,0.204456,0.223900,0.167650,0.198477,1.000000,0.237654,0.178554,0.233430,...,0.149957,0.185135,0.294698,0.283691,0.017591,0.037877,0.201060,0.223399,0.263342,0.102492
6,BAJAJFINSV,0.356547,0.398041,0.249392,0.248090,0.393683,0.237654,1.000000,0.748723,0.346261,...,0.213243,0.304497,0.280169,0.456570,0.234842,0.204276,0.329527,0.201133,0.463107,0.306650
7,BAJFINANCE,0.336031,0.398769,0.223142,0.296922,0.354079,0.178554,0.748723,1.000000,0.315822,...,0.137262,0.236369,0.212748,0.381616,0.174425,0.173360,0.269039,0.229188,0.434558,0.238516
8,BEL,0.522680,0.585672,0.224594,0.156953,0.330512,0.233430,0.346261,0.315822,1.000000,...,0.163531,0.175809,0.367173,0.520365,0.120758,0.222395,0.166767,0.263415,0.435501,0.255854
9,BHARTIARTL,0.282859,0.316537,0.236810,0.146953,0.238602,0.262054,0.257664,0.291641,0.309294,...,0.272227,0.248732,0.269331,0.305352,0.193183,0.272352,0.276037,0.247927,0.354121,0.259131
10,BPCL,0.455289,0.495117,0.174973,0.215787,0.222936,0.215531,0.345286,0.272608,0.505802,...,0.205494,0.156373,0.415679,0.462885,0.175426,0.201632,0.275086,0.212755,0.401651,0.211945
11,BRITANNIA,0.130655,0.133400,0.231736,0.426896,0.130775,0.094707,0.225478,0.207936,0.073187,...,0.187936,0.405008,0.109019,0.118834,0.117657,0.129664,0.073109,0.034251,0.181814,0.169110
12,CIPLA,0.094238,0.091118,0.231114,0.147018,0.085260,0.043536,0.135928,0.053728,0.082404,...,0.414759,0.073227,0.068966,0.131112,0.079022,0.052199,0.107529,0.136473,0.133328,0.087595
13,COALINDIA,0.494534,0.546202,0.243537,0.194986,0.332553,0.225770,0.279739,0.280246,0.620262,...,0.177471,0.213072,0.406315,0.535425,0.095263,0.178173,0.238336,0.254629,0.321221,0.235794
14,DRREDDY,0.164552,0.160972,0.235448,0.149961,0.091461,0.104890,0.257756,0.088308,0.131475,...,0.396686,0.110615,0.200125,0.207222,0.223212,0.220019,0.139991,0.168870,0.251558,0.279839
15,EICHERMOT,0.331647,0.269610,0.290339,0.257914,0.286161,0.276130,0.241356,0.189578,0.284223,...,0.175283,0.172375,0.316620,0.314499,0.143776,0.189578,0.268206,0.234639,0.304244,0.262235
16,GRASIM,0.344468,0.356102,0.258184,0.344453,0.367053,0.200661,0.435099,0.368980,0.337925,...,0.218122,0.282995,0.336304,0.463646,0.179943,0.175110,0.368297,0.241469,0.590116,0.245002
17,HCLTECH,0.139916,0.152640,0.279181,0.117484,0.107496,0.124516,0.267826,0.183187,0.224041,...,0.156099,0.209540,0.269334,0.268719,0.629079,0.548280,0.199441,0.207422,0.205442,0.580667
18,HDFCBANK,0.338118,0.375305,0.110238,0.264323,0.424931,0.182233,0.318705,0.331632,0.330752,...,0.071820,0.108654,0.204986,0.380764,0.045286,0.204667,0.188021,0.102739,0.360209,0.193599
19,HDFCLIFE,0.216839,0.247059,0.141669,0.206022,0.251479,0.191902,0.347351,0.307101,0.251302,...,0.168518,0.214307,0.224166,0.275177,0.115449,0.119529,0.226622,0.202129,0.241819,0.194261
20,HEROMOTOCO,0.208576,0.202512,0.248153,0.180187,0.172582,0.406801,0.236211,0.171239,0.087771,...,0.220462,0.212351,0.290746,0.287774,0.108665,0.111243,0.302480,0.218545,0.295383,0.204583
21,HINDALCO,0.304966,0.337762,0.062547,0.212252,0.227375,0.216860,0.296242,0.254539,0.375871,...,0.254427,0.180976,0.364959,0.630099,0.161044,0.236387,0.249438,0.268630,0.313590,0.262244
22,HINDUNILVR,-0.000796,0.002376,0.107865,0.269889,0.009843,0.124955,0.139454,0.127433,-0.058291,...,0.051338,0.412071,0.088024,0.084734,0.145345,0.131313,0.187477,0.083964,0.165126,0.185425
23,ICICIBANK,0.394584,0.442289,0.164303,0.158839,0.636786,0.108522,0.415419,0.350008,0.313735,...,0.202726,0.120592,0.199674,0.345279,0.166489,0.168655,0.146474,0.121659,0.430208,0.221655
24,INDUSINDBK,0.391347,0.422431,0.129152,0.180855,0.339661,0.206118,0.422960,0.406266,0.308607,...,0.122917,0.273550,0.333359,0.396258,0.085590,0.103153,0.240433,0.199126,0.345066,0.186573
25,INFY,0.115149,0.149400,0.121671,0.104310,0.086467,-0.003487,0.241348,0.197446,0.164705,...,0.143073,0.245193,0.181710,0.180954,0.707884,0.649146,0.215072,0.150991,0.224565,0.571208
26,ITC,0.245803,0.273774,0.174046,0.275550,0.275001,0.140413,0.303636,0.304404,0.230195,...,0.186995,0.302655,0.188564,0.257269,0.152274,0.217816,0.318261,0.151491,0.260144,0.233139
27,JSWSTEEL,0.405664,0.434606,0.276060,0.333566,0.365966,0.223461,0.447526,0.390934,0.458783,...,0.252222,0.235532,0.408712,0.794189,0.209291,0.268989,0.322128,0.256977,0.546643,0.360374
28,KOTAKBANK,0.243752,0.305838,0.139795,0.181202,0.292039,0.082628,0.273104,0.315904,0.266514,...,0.089100,0.197429,0.160206,0.262726,0.115565,0.174738,0.168053,0.081005,0.334770,0.245812
29,LT,0.483136,0.513974,0.235883,0.223101,0.352081,0.175763,0.398992,0.378919,0.591401,...,0.167209,0.168087,0.352993,0.483848,0.217062,0.210315,0.231900,0.185279,0.473174,0.319899
30,M&M,0.304545,0.319381,0.251029,0.140121,0.235556,0.271628,0.337684,0.267973,0.369498,...,0.285570,0.169598,0.400987,0.427432,0.174295,0.219419,0.285280,0.249013,0.418644,0.299971
31,MARUTI,0.315659,0.302342,0.194062,0.260366,0.260371,0.342005,0.329276,0.281244,0.224642,...,0.200872,0.207816,0.405831,0.395828,0.164892,0.147973,0.332279,0.183321,0.349174,0.205206
32,NESTLEIND,0.115017,0.087843,0.224446,0.282631,0.100344,0.179005,0.273745,0.246975,0.065317,...,0.141183,0.375731,0.147040,0.103308,0.114495,0.054905,0.236875,0.136674,0.278184,0.149708
33,NTPC,0.545960,0.610464,0.194129,0.222064,0.394813,0.202560,0.391226,0.328260,0.607886,...,0.230246,0.187078,0.409924,0.533943,0.109945,0.189870,0.334051,0.235736,0.448524,0.202935
34,ONGC,0.484910,0.521803,0.173658,0.128654,0.313449,0.187871,0.305737,0.316297,0.572377,...,0.228145,0.177229,0.436927,0.491860,0.168162,0.233515,0.192695,0.211585,0.404519,0.288967
35,POWERGRID,0.403946,0.511696,0.178438,0.111665,0.294693,0.168364,0.307034,0.245101,0.544756,...,0.246122,0.150893,0.355057,0.502428,0.097295,0.151609,0.208609,0.200542,0.396684,0.166631
36,RELIANCE,0.487097,0.512736,0.234728,0.294963,0.423456,0.246961,0.407201,0.413342,0.492507,...,0.293116,0.207763,0.386583,0.441104,0.247971,0.266063,0.329323,0.282779,0.490382,0.364313
37,SBILIFE,0.289193,0.284613,0.160706,0.220352,0.183053,0.190211,0.405717,0.335101,0.209939,...,0.131142,0.210613,0.224283,0.232113,0.175014,0.154585,0.219543,0.170800,0.266797,0.246338
38,SBIN,0.544697,0.579516,0.182850,0.107866,0.516122,0.154854,0.419859,0.397696,0.580213,...,0.122857,0.117567,0.363321,0.489624,0.162862,0.193755,0.223221,0.276491,0.425494,0.243531
39,SHRIRAMFIN,0.410298,0.469890,0.291768,0.202540,0.448564,0.301142,0.468791,0.461618,0.475480,...,0.210963,0.187778,0.362474,0.436920,0.113654,0.227147,0.254687,0.228691,0.468239,0.298607
40,SUNPHARMA,0.166256,0.215856,0.286227,0.202262,0.143991,0.149957,0.213243,0.137262,0.163531,...,1.000000,0.172295,0.305911,0.260971,0.147690,0.164001,0.214335,0.256380,0.232441,0.192644
41,TATACONSUM,0.203847,0.220655,0.096700,0.244278,0.139747,0.185135,0.304497,0.236369,0.175809,...,0.172295,1.000000,0.188062,0.225777,0.271634,0.212756,0.311262,0.185995,0.244972,0.249107
42,TATAMOTORS,0.324071,0.339241,0.212357,0.105847,0.232145,0.294698,0.280169,0.212748,0.367173,...,0.305911,0.188062,1.000000,0.513416,0.248889,0.279026,0.274323,0.222437,0.353946,0.311797
43,TATASTEEL,0.423563,0.466043,0.254731,0.287050,0.370957,0.283691,0.456570,0.381616,0.520365,...,0.260971,0.225777,0.513416,1.000000,0.235867,0.283648,0.293416,0.218748,0.471722,0.331808
44,TCS,0.115790,0.132423,0.106846,0.166699,0.094669,0.017591,0.234842,0.174425,0.120758,...,0.147690,0.271634,0.248889,0.235867,1.000000,0.578882,0.145475,0.122021,0.238679,0.591427
45,TECHM,0.141677,0.148034,0.169118,0.162959,0.136469,0.037877,0.204276,0.173360,0.222395,...,0.164001,0.212756,0.279026,0.283648,0.578882,1.000000,0.243389,0.150751,0.269904,0.599253
46,TITAN,0.283281,0.296148,0.253361,0.307404,0.145931,0.201060,0.329527,0.269039,0.166767,...,0.214335,0.311262,0.274323,0.293416,0.145475,0.243389,1.000000,0.194346,0.353920,0.259623
47,TRENT,0.190412,0.201076,0.089516,0.223094,0.199748,0.223399,0.201133,0.229188,0.263415,...,0.256380,0.185995,0.222437,0.218748,0.122021,0.150751,0.194346,1.000000,0.295226,0.150452
48,ULTRACEMCO,0.361152,0.402489,0.272951,0.280647,0.397024,0.263342,0.463107,0.434558,0.435501,...,0.232441,0.244972,0.353946,0.471722,0.238679,0.269904,0.353920,0.295226,1.000000,0.291504
49,WIPRO,0.224003,0.238986,0.223738,0.140642,0.207802,0.102492,0.306650,0.238516,0.255854,...,0.192644,0.249107,0.311797,0.331808,0.591427,0.599253,0.259623,0.150452,0.291504,1.000000

In [38]:
Stock_correlation = corr_df.to_csv('Stock_correlation.csv', index = False)

In [39]:
#month wise gainers and losers

all_stocks_df = pd.concat(cleaned_dfs.values(), ignore_index=True)

monthly_stock = all_stocks_df.groupby(['ticker', 'month']).agg(open=('open', 'first'), close=('close', 'last'))
monthly_stock['monthly_returns'] = (monthly_stock['close'] - monthly_stock['open']) / monthly_stock['open']
monthly_returns_df = monthly_stock.reset_index()

In [40]:
monthly_returns_df

       ticker    month    open    close  monthly_returns
0    adanient  2023-10  2418.0  2294.65        -0.051013
1    adanient  2023-11  2299.0  2358.55         0.025903
2    adanient  2023-12  2370.0  2848.95         0.202089
3    adanient  2024-01  2852.3  3142.00         0.101567
4    adanient  2024-02  3156.9  3285.40         0.040704
..        ...      ...     ...      ...              ...
695     wipro  2024-07   517.9   522.00         0.007917
696     wipro  2024-08   523.0   538.40         0.029446
697     wipro  2024-09   538.4   541.45         0.005665
698     wipro  2024-10   540.2   551.80         0.021474
699     wipro  2024-11   551.7   571.65         0.036161

[700 rows x 5 columns]

In [41]:
monthly_returns_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ticker           700 non-null    object
 1   month            700 non-null    object
 2   open             700 non-null    float64
 3   close            700 non-null    float64
 4   monthly_returns  700 non-null    float64
dtypes: float64(3), object(2)
memory usage: 27.5+ KB

In [42]:
split_monthdata = {}

normalizing_data = monthly_returns_df

for ticker, group in normalizing_data.groupby('month'):
    split_monthdata[ticker] = group

In [43]:
split_monthdata['2023-10']

         ticker    month      open     close  monthly_returns
0      adanient  2023-10   2418.00   2294.65        -0.051013
14   adaniports  2023-10    826.00    784.75        -0.049939
28   apollohosp  2023-10   5138.95   4819.90        -0.062085
42   asianpaint  2023-10   3166.10   2995.70        -0.053820
56     axisbank  2023-10   1035.00    981.85        -0.051353
70   bajaj-auto  2023-10   5065.00   5314.05         0.049171
84   bajajfinsv  2023-10   1530.25   1569.55         0.025682
98   bajfinance  2023-10   7780.80   7492.65        -0.037033
112         bel  2023-10    137.90    133.25        -0.033720
126  bhartiartl  2023-10    918.25    914.40        -0.004193
140        bpcl  2023-10    174.25    174.63         0.002181
154   britannia  2023-10   4524.80   4426.50        -0.021725
168       cipla  2023-10   1184.00   1200.00         0.013514
182   coalindia  2023-10    297.05    314.25         0.057903
196     drreddy  2023-10   1117.38   1073.51        -0.039261
210   eichermot  2023-10   3426.90   3295.55        -0.038329
224      grasim  2023-10   1920.46   1879.23        -0.021469
238     hcltech  2023-10   1232.50   1276.00         0.035294
252    hdfcbank  2023-10   1527.00   1476.50        -0.033071
266    hdfclife  2023-10    634.45    618.35        -0.025376
280  heromotoco  2023-10   3058.00   3088.35         0.009925
294    hindalco  2023-10    483.10    459.50        -0.048851
308  hindunilvr  2023-10   2490.00   2484.00        -0.002410
322   icicibank  2023-10    951.60    915.35        -0.038094
336  indusindbk  2023-10   1432.00   1441.30         0.006494
350        infy  2023-10   1436.05   1368.40        -0.047108
364         itc  2023-10    441.00    428.40        -0.028571
378    jswsteel  2023-10    776.55    736.35        -0.051767
392   kotakbank  2023-10   1730.00   1739.40         0.005434
406          lt  2023-10   3040.50   2929.05        -0.036655
420         m&m  2023-10   1597.20   1458.60        -0.086777
434      maruti  2023-10  10709.80  10392.30        -0.029646
448   nestleind  2023-10   2250.69   2423.48         0.076772
462        ntpc  2023-10    244.35    235.80        -0.034991
476        ongc  2023-10    189.30    186.15        -0.016640
490   powergrid  2023-10    198.75    202.15         0.017107
504    reliance  2023-10   1164.97   1143.95        -0.018043
518     sbilife  2023-10   1302.15   1367.85         0.050455
532        sbin  2023-10    596.60    565.55        -0.052045
546  shriramfin  2023-10   1938.00   1879.85        -0.030005
560   sunpharma  2023-10   1159.55   1088.60        -0.061188
574  tataconsum  2023-10    859.32    889.44         0.035051
588  tatamotors  2023-10    632.60    628.65        -0.006244
602   tatasteel  2023-10    129.00    118.75        -0.079457
616         tcs  2023-10   3534.20   3368.75        -0.046814
630       techm  2023-10   1220.60   1133.15        -0.071645
644       titan  2023-10   3148.80   3189.65         0.012973
658       trent  2023-10   2074.30   2154.70         0.038760
672  ultracemco  2023-10   8289.00   8422.25         0.016076
686       wipro  2023-10    406.45    381.80        -0.060647

In [44]:
result_data = {}

for month,df in split_monthdata.items():
  gainers = df.nlargest(5, 'monthly_returns')
  losers = df.nsmallest(5, 'monthly_returns')

  monthly_gl_df = pd.concat([gainers, losers]).sort_values('monthly_returns', ascending=False)


  result_data[month] = monthly_gl_df

In [45]:
result_data['2024-01']

         ticker    month     open    close  monthly_returns
479        ongc  2024-01   206.00   252.25         0.224515
549  shriramfin  2024-01  2055.55  2466.80         0.200068
17   adaniports  2024-01  1026.55  1207.65         0.176416
129  bhartiartl  2024-01  1031.95  1170.70         0.134454
73   bajaj-auto  2024-01  6770.00  7667.55         0.132578
381    jswsteel  2024-01   880.25   818.65        -0.069980
213   eichermot  2024-01  4145.00  3839.60        -0.073679
269    hdfclife  2024-01   647.00   576.60        -0.108810
45   asianpaint  2024-01  3403.00  2957.85        -0.130811
255    hdfcbank  2024-01  1706.00  1462.55        -0.142702

In [46]:
jan2024_df = result_data['2024-01'].to_csv('jan2024_df.csv', index = False)

In [47]:
for month, df in result_data.items():
  df.to_csv(f"cleaned{month}.csv",index = False)